### ISSUE TITLE
geojson-layer does not suppor popup

### ISSUE THREAD

**Issue by seadiaz** [miguelcobain/ember-leaflet#108]
When I try to bind a popup into a geojson layer I got the error message "Uncaught TypeError: this.get(...)._layer.bindPopup is not a function".

On Leaflet documentation for geojson layer says...

```
L.geoJSON(data, {
    style: function (feature) {
        return {color: feature.properties.color};
    }
}).bindPopup(function (layer) {
    return layer.feature.properties.description;
}).addTo(map);
```

I think that DivOverlayableMixin is missing on geojson layer, am i right?

**Comment by miguelcobain** [comment]
@seadiaz very likely that is the problem.

**Comment by miguelcobain** [comment]
Should be fixed on `3.0.2`.

**Comment by seadiaz** [comment]
👍🏻

**Comment by allthesignals** [comment]
I'm seeing this error on route transitions, probably when it tears down the parcel layer:

`Uncaught TypeError: this.get(...)._layer.unbindPopup is not a function`

```
{{#geojson-layer geoJSON=parcel.geojson}}
 {{#popup-layer}}
  <h3>{{parcel.name}}</h3>
  Address: {{parcel.address}}
 {{/popup-layer}}
{{/geojson-layer}}
```

Any thoughts? Seems like popups work, but teardown breaks things. 

Thanks!

**Comment by digitalsadhu** [comment]
Also seeing this issue as described by @allthesignals 
Popup renders ok in the first place but teardown throws the `this.get(...)._layer.unbindPopup` error

**Comment by miguelcobain** [comment]
Can someone PR a failing test with this bug? It would make things quicker when I have the chance to take a look at it.

**Comment by digitalsadhu** [comment]
I don't have time to do so just now (deadlines deadlines) but am digging through source code and contribute findings.

So far I have verified that 
A. the parent component that is fetched [here](https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/popup-layer.js#L61) is the expected geojson layer
B. the geojson layer does not have the unbindpopup method. Unsure why, leaflet docs suggest it should (via inheritance). I wonder if its related to geojson layers and layer groups etc. It may just be that the popup layer needs to handle the geojson layer a little differently to be able to call unbind popup.

Digging continues...

**Comment by digitalsadhu** [comment]
Ok got it.
Leaflet 0.7's geojson layer does not have unbindpopup, 1.0 and onwards does.

**Comment by miguelcobain** [comment]
Oh. :/
What is the equivalent of that function on leaflet 0.7?
we can test if that function exists before calling it.

**Comment by digitalsadhu** [comment]
looking into that at the moment. It has bindpopup but im not seeing anything obvious to unbind. Will continue looking into it.

**Comment by digitalsadhu** [comment]
Sorry man, I'm going to have to give up for now. I can't work out how you were supposed to unbind popups in leaflet 0.7. but I have some clues here that might help.

It changed in leaflet between [this commit](https://github.com/Leaflet/Leaflet/commit/eb82d4ee42e0959b63c3ee16a7992558a9899df8#diff-01d2b1169c18b2d745910b7f62475ee9) and [this commit](https://github.com/Leaflet/Leaflet/commit/5110298c459356d745e2bc36e4820e3b520a1cab#diff-01d2b1169c18b2d745910b7f62475ee9)

The PR for when it was added is [here](https://github.com/Leaflet/Leaflet/pull/896) probably give you a clue at least.

**Comment by allthesignals** [comment]
I can work on a failing test later tonight, thanks for looking into this @digitalsadhu

**Comment by miguelcobain** [comment]
@digitalsadhu @allthesignals are you both using leaflet 0.7? If so, what is exactly the reason?

**Comment by allthesignals** [comment]
@miguelcobain I believe there were some weird dependency issues with other leaflet addons like marker cluster and tile cache (they rely on 0.7). I need to check this again, though, which I can do later. Thanks.

**Comment by digitalsadhu** [comment]
Another dependency we have Cant be upgraded yet.
