### ISSUE TITLE
Tooltip permanent isn't working

### ISSUE THREAD

**Issue by timmyomahony** [miguelcobain/ember-leaflet#111]
Hey, 

I notice that when using the tooltips, if I try to use `permanent=true` the text within the tooltip doesn't display: 

```
{{#marker-layer location=location icon=icon}}
  {{#tooltip-layer permanent=true}}
    test text
  {{/tooltip-layer}}
{{/marker-layer}}
```

Without `permanent=true` the tooltip and text is showing OK on hover, but when removed the tooltip is there but doesn't have any text content.

**Comment by jamesdixon** [comment]
I can confirm this on  v3.0.4

**Comment by miguelcobain** [comment]
@timmyomahony @jamesdixon can you please try if `v3.0.5` fixed this issue?

**Comment by jamesdixon** [comment]
@miguelcobain works like a charm. Thank you!
