### ISSUE TITLE
Can't use contextual component syntax for helpers when overriding & extending EmberLeafletMap component

### ISSUE THREAD

**Issue by allthesignals** [miguelcobain/ember-leaflet#120]
Documentation uses contextual component syntax to call helpers. Although it's trivial to switch from `{{layers.tile}}` to `{{tile-layer}}`, this can cause some confusion when needing to override and extend the component to do things like re-position the zoom control. Is this better solved by further documentation or a fix?

```
Ember      : 2.9.1
Ember Data : 2.10.0
jQuery     : 3.1.1
"ember-leaflet": "2.2.7"
```

Does not work after extending `leaflet-map` component:
```
{{#leaflet-map lat=42.1 lng=-71 zoom=12 as |layers|}}
  {{layers.tile url='http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'}}
{{/leaflet-map}}
```

**Comment by miguelcobain** [comment]
Which component are you extending?

**Comment by allthesignals** [comment]
@miguelcobain oops, here you go:

```
import EmberLeafletMap from 'ember-leaflet/components/leaflet-map';
export default EmberLeafletMap.extend({
});
```

**Comment by miguelcobain** [comment]
@allthesignals So, if you do that you can't use contextual components anymore? Is that it?

**Comment by byrnedo** [comment]
@miguelcobain is there a workaround for this?

**Comment by miguelcobain** [comment]
This is just how ember component inheritance works. It overrides the layout property. You have to either copy paste the template or import it and assign it.
