### ISSUE TITLE
bounds does not work with L.CRS.Simple

### ISSUE THREAD

**Issue by jelhan** [miguelcobain/ember-leaflet#126]
I'm facing a strange bug with `bounds` parameter. It seems to be ignored until first resize of window. The overlay image is at left top corner of map but it should be in center.

A simple code to reproduce:
```
{{#leaflet-map
  bounds=bounds
  crs=crs
  minZoom=-3
}}
  {{image-layer
    bounds=bounds
    imageUrl='https://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg'
  }}
{{/leaflet-map}}
```

```
import Ember from 'ember';
/* global L */

const { Component, computed } = Ember;

export default Component.extend({
  bounds: computed(function() {
    let w = 691;
    let h = 541;

    let southWest = L.CRS.Simple.unproject({ x: 0, y: h });
    let northEast = L.CRS.Simple.unproject({ x: w ,y: 0 });

    let bounds = new L.LatLngBounds(southWest, northEast);
    return bounds;
  }),
  crs: L.CRS.Simple
});
```

I tried to debug but doesn't have a clue what's happening.

It's not related to leaflet cause plain leaflet is working: https://jsfiddle.net/zk2k6q4c/

**Comment by miguelcobain** [comment]
@jelhan don't know if it matters, but did you try specifying `maxBounds= bounds` in the leaflet-map, like in the fiddle you linked?

**Comment by jelhan** [comment]
Yeah of course. Just deleted it to reduce code even more. It doesn't make any difference.

**Comment by jelhan** [comment]
I tried to implement the exact same code ember-leaflet is calling in exact same order at it is called but wasn't able to reproduce the bug in plain leaflet: https://jsfiddle.net/zk2k6q4c/1/ Would appreciate any hint.

**Comment by jelhan** [comment]
Arghs, it was caused by a side effect of ember-bootstrap tabs. It's working fine outside of tab content. Sorry for noice.
