### ISSUE TITLE
ember-leaflet-contextmenu

### ISSUE THREAD

**Issue by jelhan** [miguelcobain/ember-leaflet#127]
Just published ember-leaflet-contextmenu: https://github.com/jelhan/ember-leaflet-contextmenu

It doesn't support all options yet, but working for simple use cases. Feel free to add it to Addon section of website.

**Comment by miguelcobain** [comment]
@jelhan can you PR that?
The source of the ember-leaflet website is in this repo under `tests/dummy`. It is a normal ember app.
