### ISSUE TITLE
Ember leaflet is not displaying anything, on changing css property it shows but does not work well

### ISSUE THREAD

**Issue by jiteshgupta1995** [miguelcobain/ember-leaflet#139]
I am using Ember-leaflet for my ember application. I followed every step from installation to usage but somehow it is not showing anything. I inspected the elements and found property overflow:hidden. I changed to overflow:visible then map was showing but on zooming in and out, image expands awkwardly.

I am using in my template.hbs

```
{{#leaflet-map lat=lat lng=lng zoom=zoom}}
  {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
{{/leaflet-map}}
```
and in my template.js

```
export default Ember.Controller.extend({
  lat: 45.519743,
  lng: -122.680522,
  zoom: 10
});
```
reference used from http://www.ember-leaflet.com . Do I required to import or include any CSS or JS file. Any help?

**Comment by miguelcobain** [comment]
@jiteshgupta1995 the usual suspect is that people skip this part of the docs

> Reminder: The leaflet map container needs to be styled to have some size. If you don't see any container at all, that's probably because you forgot to style it. You can target leaflet containers in css using the .leaflet-container class or providing an id or class attribute in your {{#leaflet-map component.
in http://www.ember-leaflet.com/docs/container

Can you try specifying
```css
.leaflet-container {
  height: 300px;
}
```
in your app.css file?

**Comment by jiteshgupta1995** [comment]
@miguelcobain thanks for the reply. It works perfectly great should have read docs carefully, Sorry my mistake. Can you please tell me how to use different template because I could understand which url to pass to tile-layer.

**Comment by miguelcobain** [comment]
> Can you please tell me how to use different template because I could understand which url to pass to tile-layer.

You need to pass an url of a tile server. There are many free ones, and also paid ones.
