### ISSUE TITLE
Icons/Map Tiles getting messed up when deployed to production

### ISSUE THREAD

**Issue by steveclarkin** [miguelcobain/ember-leaflet#146]
I'm seeing a weird issue where the Icons and Map tiles are getting messed up when I deploy my app to production. The issue is probably best described with a screenshot:

[Running on dev server](https://i.imgsafe.org/d937a636cb.png)

[Running on production](https://i.imgsafe.org/d9382452b2.png)

Production deployment is via "ember deploy" to S3/Cloudfront.

I suspect the problem is somehow being caused during the asset compilation/minification process?

I'm using ember 2.12.0 and ember-leaflet 3.0.11

Any ideas, or suggested steps to diagnose this? TIA

**Comment by buschtoens** [comment]
Can you release the source code or extract the map into a demo repository?

If not, could you please copy the DOM that is produced by the `{{leaflet-map}}` component? Please also include the `vendor.css` output.

My best guess is that the Leaflet.js stylesheets are somehow missing or incomplete.

This is what you get when `vendor.css` is removed from www.ember-leaflet.com.
![image](https://cloud.githubusercontent.com/assets/834636/24539067/00cd34e4-15ed-11e7-815b-23142199e15e.png)

**Comment by buschtoens** [comment]
The marker layer offset also appears similar.

![image](https://cloud.githubusercontent.com/assets/834636/24539127/4c48a80e-15ed-11e7-98a5-943a87a79366.png)

**Comment by steveclarkin** [comment]
Thank you @buschtoens ! 

I haven't fixed the issue yet, but you've certainly put me on the right track. Indeed, vendor.css isn't loading. I don't know how I missed this, but i'm getting the following error in Chrome:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://app.myapp.com.au/assets/vendor-0465cfb5dfffac47bcdd89826e34f76a.css' with computed SHA-256 integrity 'K6rZciczeAaGDbzJK3vimSJkwJ5GLTQRlH44q39Hswk='. The resource has been blocked.`

I confirmed that the vendor.css does in fact contain the leaflet css, so i'm confident that once I fix the above issue, leaflet will work as expected. I'll post back once i've identified the root cause.

**Comment by steveclarkin** [comment]
Problem solved!

For whatever reason (most likely of my own doing), CloudFront wasn't invalidating vendor.css. I determined this by comparing the SHA hashes between the origin (S3) and CF, and discovered they were different.

Sorry to waste your time on a non leaflet issue, but thanks again for your help!
