### ISSUE TITLE
2 new addons for ember-leaflet 

### ISSUE THREAD

**Issue by dio-el-claire** [miguelcobain/ember-leaflet#148]
[ember-leaflet-google-mutant-layer](https://github.com/dio-el-claire/ember-leaflet-google-mutant-layer)
[ember-leaflet-heatmap-layer](https://github.com/dio-el-claire/ember-leaflet-heatmap-layer)

**Comment by miguelcobain** [comment]
Nice job!
We already had https://github.com/willviles/ember-leaflet-heatmap though. Might be worth to join forces.

Do you mind PRing these two new addons to the leaflet web page addons list?

**Comment by dio-el-claire** [comment]
Thanks!

For me  https://github.com/willviles/ember-leaflet-heatmap is not well:)
Yes, I mind PRing addons to the leaflet web page addons list.

**Comment by miguelcobain** [comment]
This is the file you should change: https://github.com/miguelcobain/ember-leaflet/blob/master/tests/dummy/app/templates/addons.hbs

**Comment by willviles** [comment]
@dio-el-claire - I'd be interested to know what's not working with Ember Leaflet Heatmap. Ember Leaflet Heatmap Layer looks pretty similar, apart from you're importing the leaflet-heatmap plugin directly as an AMD transform.
