### ISSUE TITLE
Multiple Polyline is not working

### ISSUE THREAD

**Issue by jiteshgupta1995** [miguelcobain/ember-leaflet#150]
I am trying to plot a path using multiple lat and long something like demonstrated here [Ember leaflet Multi option polyline](http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/). I have also gone through the docs for [Adding layers](http://www.ember-leaflet.com/docs/adding-layers) but unable to make it look like Ember leaflet Multi option polyline Demo mentioned in the above link.
I am getting Error as 

> ember.debug.js:17636 TypeError: Bind must be called on a function

Is there any way to make it work?

**Comment by miguelcobain** [comment]
Can you show the code you're using?

**Comment by jiteshgupta1995** [comment]
Code in template.hbs
`{{#leaflet-map lat=lat lng=lng zoom=zoom}}`
`           {{tile-layer url="http://a.tile.openstreetmap.org/{z}/{x}/{y}.png"}}`
`           {{multi-options-polyline latlngs=mapContent options=mapContentOptions}}`
`{{/leaflet-map}}`

Code in controller.js
```
                var options = [
                        {color: '#0000FF'}, 
                        {color: '#0040FF'},
                        {color: '#0040FF'},
                        {color: '#0040FF'},
                        {color: '#0040FF'}
                    ];
                    var a = user.get("location");
                    var track={};
                    var i=0;
                    for(var key in a){
                            track[i] = {
                                lat:a[key][0],
                                lng:a[key][1]
                            };
                            i++;
                    }
                    self.set('mapContentOptions',options);
                    self.set('mapContent',track);
```

I don't know if the value of mapContentOptions and mapContent I am passing are right or wrong. Thanks for quick Reply

**Comment by miguelcobain** [comment]
Ah, so you're using this addon: https://github.com/mjanda/ember-leaflet-multi-options-polyline

You should open this issue there, please.

**Comment by jiteshgupta1995** [comment]
Could have raised the issue there, the addon is not actively handle. Can you tell me if this [http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/](http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/) can be achieved without using that addon or can you suggest some other addon.

**Comment by miguelcobain** [comment]
@jiteshgupta1995 can you create an ember-twiddle that reproduces that problem? It would be easier.

**Comment by jiteshgupta1995** [comment]
I not able to reproduce same error and getting different Error but Code is same:

> Cannot read property 'copyBaseOptions' of undefined

[Twiddle link](https://ember-twiddle.com/7e71d1a8e23c82abe1ce01324c87a22f?openFiles=controllers.application.js%2C)
Can you have a look and let me know. Thanks @miguelcobain

**Comment by miguelcobain** [comment]
@jiteshgupta1995 doesn't look like you're passing the options in the correct format.
Please read the projects readme: https://github.com/hgoebl/Leaflet.MultiOptionsPolyline

**Comment by jiteshgupta1995** [comment]
@miguelcobain I have gone through that README file but nothing makes sense to me. Can you Create a working version of **Leaflet Multi Polyline** and share me Ember Twiddle link.

**Comment by jiteshgupta1995** [comment]
Hi @miguelcobain . Can you create a demo of the Leaflet Multi Polyline.

**Comment by mjanda** [comment]
Clearly, your mapContentOptions don't have proper format - they should contains something like this:

```
{
    multiOptions: {
        optionIdxFn: function (latLng) {
            var i,
                altThresholds = [800, 900, 1000, 1100, 1200, 1300, 1400, 1500];

            for (i = 0; i < altThresholds.length; ++i) {
                if (latLng.alt <= altThresholds[i]) {
                    return i;
                }
            }
            return altThresholds.length;
        },
        options: [
            {color: '#0000FF'}, {color: '#0040FF'}, {color: '#0080FF'},
            {color: '#00FFB0'}, {color: '#00E000'}, {color: '#80FF00'},
            {color: '#FFFF00'}, {color: '#FFC000'}, {color: '#FF0000'}
        ]
    },
    weight: 5,
    lineCap: 'butt',
    opacity: 0.75,
    smoothFactor: 1
}
```

My own working code.

```
  mapContentOptions: function() {
    let zones = this.get('histogramZones');
    let zoneField = this.get('histogramFor');

    return {
      multiOptions: {
        optionIdxFn: function(latLng) {
          if (latLng[zoneField]) {
            for (let i = 0; i < zones.zones.length; ++i) {
              if (latLng[zoneField] <= zones.zones[i]) {
                return i;
              }
            }
          }
          return zones.zones.length - 1;
        },

        options: zones.colors
      },
      weight: 5,
      lineCap: 'butt',
      opacity: 1,
      smoothFactor: 1,
      className: 'coloredLine'
    };
  }.property('histogramZones', 'histogramFor'),
```

Of course, you'll have to implement your `optionIdxFn` and fill options properly. But https://github.com/hgoebl/Leaflet.MultiOptionsPolyline should help you there.
