### ISSUE TITLE
Errors with zoom animation

### ISSUE THREAD

**Issue by Techn1x** [miguelcobain/ember-leaflet#156]
I've got a map with about 200 markers on it. I have each marker popup binded with popupOpen=(readonly (eq asset.id selectedAsset.id))

I zoom out a bit, I click on an asset in an external panel to set the selectedAsset, like so;
```
this.set('selectedAsset', asset);
var map = this.get('map');
map.setView(asset.get('location'),10);
```

This then causes the following error
```
Uncaught TypeError: Cannot set property '_leaflet_pos' of undefined
    at Object.setPosition (DomUtil.js:204)
    at NewClass._animateZoom (Popup.js:217)
    at NewClass.fire (Events.js:185)
    at NewClass._animateZoom (Map.js:1566)
    at NewClass.<anonymous> (Map.js:1547)
```

This happens every time I click on a marker I haven't clicked on yet, whenever the map is required to zoom. If I am already at zoom level 10 and only panning is required, the error does not occur.

As such, the error also goes away when using map.panTo(asset.get('location')); OR when zoomAnimation=false in the map layer. So zooming is definitely an issue here..

What's also interesting, is that clicking on a marker directly, does not cause this issue.

Any ideas what might be wrong, or perhaps a workaround?

Thanks

**Comment by Techn1x** [comment]
After dealing with this bug for almost 2 weeks, I think I know more about what the issue is, and I have found a workaround.

I think the issue is to do with the order in which a popup opens, and zoom animations.

I believe it previously worked when clicking on a marker directly, because the markers' default action is to open its' popup, which must occur at a different time to when I open popups externally via popupOpen binding on the popup-layer.

I also know that if I remove the popupOpen binding code, and just focus on the zoom, it works, as demonstrated here;

**Doesn't work (causes error shown in OP);**
```javascript
this.set('selectedAsset', asset); // Opens a marker popup via popupOpen=(readonly (eq asset.id selectedAsset.id)) binding
var map = this.get('map');
map.setView(asset.get('location'),10);
```
**Does work (popup left closed);**
```javascript
/*this.set('selectedAsset', asset);*/
var map = this.get('map');
map.setView(asset.get('location'),10);
```
**Also works (panning instead of zooming);**
```javascript
this.set('selectedAsset', asset);
var map = this.get('map');
/*map.setView(asset.get('location'),10);*/
map.panTo(asset.get('location'));
```

I have a strong feeling it's related to the similar popup-timing issues here https://github.com/miguelcobain/ember-leaflet/issues/131

---

My workaround is to only have the popup-layer open its popup via popupOpen binding, and remove the markers' default action to open it's own popup onClick, as described here https://github.com/miguelcobain/ember-leaflet/issues/131#issuecomment-300816255 like so;

```javascript
// app/components/marker-that-will-not-open-its-popup-on-click.js
import MarkerLayer from 'ember-leaflet/components/marker-layer';

export default MarkerLayer.extend({
  createLayer() {
    let layer = this._super(...arguments);
    layer._openPopup = () => {};
    return layer;
  }
});
```

And then have the fly/zoom action occur on onPopupOpen on the marker-layer, like so;
```handlebars
{{#marker-that-will-not-open-its-popup-on-click location=asset.location onClick=(action 'selectAsset' asset) onPopupopen=(action 'zoomToSelectedAsset') icon=(if (eq asset.id selectedAsset.id) defaultMarkerIcon unselectedMarkerIcon)}}
    {{#popup-layer popupOpen=(readonly (eq asset.id selectedAsset.id)) }}
    ...
    {{/popup-layer}}
{{/marker-layer}}
```
```javascript
selectAsset: function(asset) {
    this.set('selectedAsset', asset); // Opens a marker popup via popupOpen=(readonly (eq asset.id selectedAsset.id)) binding
}
```
```javascript
zoomToSelectedItem: function() {
    var selectedItem = this.get('selectedItem');
    var map = this.get('map');
    map.flyTo(selectedItem.get('lastLocation'),10);
}
```

So now the map flying/zooming always occurs **after** the popup is completely open, which seems to work!

**Comment by ioanszabo** [comment]
As I understand, implementing this solution you did not got the error when zooming and popup is opened?

**Comment by Techn1x** [comment]
Once I implemented this workaround I was able to have the marker open its popup and have the map zoom to that location, without any errors. Hope it helps you out!

**Comment by Techn1x** [comment]
After updating to 3.1.2, Seems to be half fixed. No longer need to override the marker-layer, but still need to ensure that the fly/zoom action occurs on the markers' `onPopupopen`, rather than as part of the `selectAsset` action.
