### ISSUE TITLE
Working with bounds *and* center/zoom

### ISSUE THREAD

**Issue by muziejus** [miguelcobain/ember-leaflet#158]
In #157, I asked about how to control the map from outside the `{{leaflet-map}}` component. I've figured that out, but, in so doing, have come across a more fundamental problem that may be unsolvable.

To wit, a map can only be initialized with either `bounds` or a center of some sort and a `zoom`. My current situation looks like this
 
Template: 
```
{{#leaflet-map center=center zoom=zoom as |layers|}}
...
{{/leaflet-map}}
<ul>
{{#each places as |place|}}
  <li>
    <a {{action "recenter" place.latLng}}>{{place.name}}</a>
  </li>
{{/each}}
</ul>
```
In the controller, I have:
```
bounds: Ember.computed('places', function() {
  return L.latLngBounds(this.get('places').map(place => {
    return place.get('latLng');
  }));
}),
center: Ember.computed(function() {
  return this.get('bounds').getCenter();
}),
zoom: 8,
actions: {
  recenter(latLng) {
    this.set('center', latLng);
  }
}
```
This lets me recenter on the fly (the problem in the previous issue), but it breaks the way the template was originally set up, with `bounds=bounds` instead of `center=center zoom=zoom`. For obvious reasons, `L.latLngBounds` doesn't have a `getZoom()` that I can feed to `zoom` in the controller like I can for `center`.

So is it possible to define a map using `center` and `zoom` but then use a calculated `bounds` property to change *both* the center (yes) *and* the zoom?

**Comment by linearza** [comment]
I am working on a similar issue now, it would be nice to be able to easily switch between the two use cases

**Comment by muziejus** [comment]
I completely forgot I wrote this. I can't even remember the particular use case, but the solution seems to have been to use Leaflet's `fitBounds` method, if I understand my question right.
