### ISSUE TITLE
Prepare for FastBoot 1.0

### ISSUE THREAD

**Issue by kratiahuja** [miguelcobain/ember-leaflet#159]
This addon is compatible with FastBoot. FastBoot 1.0 no longer has the `process.env.EMBER_CLI_FASTBOOT` environment variable. This addon can still remain backward compatible for versions that set this variable by following the migration guide [here](https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c)

**Comment by shicholas** [comment]
I also got issues with bower and the latest fastboot.

**Comment by buschtoens** [comment]
@schicolas ember-leaflet does not have Bower dependencies anymore: https://github.com/miguelcobain/ember-leaflet/blob/master/README.md#installation

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-leaflet/pull/163
