### ISSUE TITLE
Map starts drifting after zoom/pan (Chrome Mobile)

### ISSUE THREAD

**Issue by wdlb** [miguelcobain/ember-leaflet#162]
We have an Ember (1.13.10) application where we use ember-leaflet (1.1.1) to show a map consisting of a TileLayer (Google Maps) and a CollectionLayer in a ContainerLayer containing the markers.

After zooming and panning a bit, the map keeps on moving, shaking and drifting in a certain direction, as shown in the gif below:

![](https://media.giphy.com/media/1fikRDKbu7w52/giphy.gif)

This only happens on Chrome Mobile, not Chrome Desktop or Firefox Mobile. Does anybody have an idea about the cause of this problem and how to fix it? Thanks a lot!

FYI, I haven't managed yet to create a Fiddle/Plunkr/... where I can reproduce this but I'm working on this.

**Comment by miguelcobain** [comment]
It would help a lot if you could provide a twiddle with this situation at ember-twiddle.com

**Comment by miguelcobain** [comment]
This shouldn't be an issue anymore on master. Please reopen if this still persists.
