### ISSUE TITLE
Tooltips & changing attributes

### ISSUE THREAD

**Issue by Techn1x** [miguelcobain/ember-leaflet#164]
I really need to bind my tooltips to the permanent property, so that when permanent changes, the tooltip refreshes and abides by this new permanent value. Currently, the tooltip only uses the permanent value it was given with when the layer was created.

What would be the best way to achieve this? I've extended the tooltip-layer and tried a number of approaches with no luck..

```handlebars
{{#each assets as |item|}}
    {{#marker-layer}}
        {{#tooltip-layer permanent=(is-recent-time item.state.status.updated_at 15)}}
            {{tooltip-content item=item}}
        {{/tooltip-layer}}
    {{/marker-layer}}
{{/each}}
```

Thanks

**Comment by sukima** [comment]
Looking at how [leaflet](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Tooltip.js#L296) handles this property it seems it is an initialization option not something that can change on the fly. I think you would have to tear down and rebuild each time. Perhaps with something like this:

```handlebars
{{#each assets as |item|}}
    {{#marker-layer}}
        {{#if (is-recent-time item.state.status.updated_at 15)}}
            {{#tooltip-layer permanent=true}}
                {{tooltip-content item=item}}
            {{/tooltip-layer}}
        {{else}}
            {{#tooltip-layer permanent=false}}
                {{tooltip-content item=item}}
            {{/tooltip-layer}}
        {{/if}}
    {{/marker-layer}}
{{/each}}
```

**Comment by Techn1x** [comment]
Thanks!! This worked a treat, and so simple!

Although, I was having a separate issue/bug with the initial positioning of tooltips being centered directly on top of the marker rather than alongside (which is then corrected by a zoom action) - and this fix exacerbates the issue because it recreates the tooltips - but at least now I have one less issue to solve!
