### ISSUE TITLE
Using on the same view with ember-modal-dialog

### ISSUE THREAD

**Issue by getaclue** [miguelcobain/ember-leaflet#169]
Hey guys,

Just ran into the issue of using a modal with the leaflet.
The modal example is the most [basic one](https://github.com/yapplabs/ember-modal-dialog) from the readme

```hbs
{{#if isShowingModal}}
    {{#modal-dialog onClose="toggleModal"
                    targetAttachment="center"
                    translucentOverlay=true
                  }}
      Oh hai there!
    {{/modal-dialog}}
  {{/if}}
```
with
```hbs
<button {{action "toggleModal"}}>Toggle Modal</button>
```

The issue was that the map was overlaying over the modal.
So I simply set the modal (`modal-overlays` modal) to have z-index of `1001` since the map is at `400` and the controls at `1000`.

Not sure if this is the hacky way to do it, or what.
Tried a search and didn't see it mentioned so I figured I would mention it here.

Cheers,
Alex

**Comment by miguelcobain** [comment]
I think there is no way around it. If the included styles clash, we need to fix them ourselves.
Thanks for the heads up!
