### ISSUE TITLE
action parameters

### ISSUE THREAD

**Issue by drewda** [miguelcobain/ember-leaflet#17]
I'm plotting a number of markers that are built from Ember Data models:

```
{{#leaflet-map id="stop-explorer-map" lat=lat lng=lng zoom=zoom}}
  {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
  {{#each model as |stop|}}
    {{marker-layer location=stop.latLng title=stop.name onMouseover="startMarkerMouseover"}}
  {{/each}}
{{/leaflet-map}}
```

I'd like to be able to modify the appropriate Ember Data model on mouseover start and end, to toggle a "selected" property. (That's going to highlight that same model in a different table view.)

I see how the `startMarkerMouseover` event in my code only receives the Leaflet raw event. Is there a way to provide parameters to the action, so I can pass the stop model in the action handler?

**Comment by drewda** [comment]
After reading https://github.com/miguelcobain/ember-leaflet/issues/10#issuecomment-161197787, I realized that the following would work:

```
{{marker-layer location=stop.latLng title=stop.name onMouseover=(action "startMarkerMouseover" stop)}}
```

Thanks for sharing your code, @radcliff.

**Comment by miguelcobain** [comment]
I really love how the only issues arising are basically normal Ember problems. :+1:

**Comment by drewda** [comment]
Good to know the name for the pattern. Thanks, @miguelcobain.
