### ISSUE TITLE
`icon` isn't promise friendly.

### ISSUE THREAD

**Issue by luketheobscure** [miguelcobain/ember-leaflet#170]
I've got a model with an asynchronous relationship that determines its type. There's no way to easily pass the icon to ember-leaflet. My workaround looks like this (which is kinda gross):

```
icon: computed('marker.pointOfInterestType.isFulfilled', function mapIcon() {
    const type = this.get('marker.pointOfInterestType');

    if (!(get(type, 'isFulfilled') && get(type, 'icon'))) { return new L.Icon.Default() }

    return L.icon({ iconUrl: get(type, 'icon') });
  }),
```

**Comment by miguelcobain** [comment]
@luketheobscure what happens if you use the icon helper?
```js
{{#marker-layer icon=(icon iconUrl=marker.pointOfInterestType.icon)}}
{{/marker-layer}}
```

**Comment by luketheobscure** [comment]
The icon helper didn't work for me. I get the error: `TypeError: src.hasOwnProperty is not a function`. This is because the hash passed to helpers isn't a normal object, it's a weird Ember `EmptyObject` that doesn't have some of the weight of a normal object prototype (things like `hasOwnProperty`. I've solved this in my own helpers by adding something like `hash = Object.assign({}, hash)`.

I'm not sure when they made the switch, but I'm on Ember v2.11.3.

**Comment by miguelcobain** [comment]
@luketheobscure what about
```hbs
{{#if marker.pointOfInterestType.icon}}
  {{#marker-layer icon=(icon iconUrl=marker.pointOfInterestType.icon)}}
    Popup
  {{/marker-layer}}
{{/if}}
```

**Comment by kaermorchen** [comment]
I've caught a bug if use [ember-mdi](https://github.com/kaermorchen/ember-mdi) + ember-leaflet.

ember-mdi have icon property inside [component](https://github.com/kaermorchen/ember-mdi/blob/master/addon/templates/components/mdi-icon.hbs).

Instead of 
`<use xlink:href="#account"></use>`
I get
`<use xlink:href="#[object Object]"></use>`

**Comment by miguelcobain** [comment]
The `hasOwnProperty` shouldn't be a problem anymore on 3.0.18.
The icon helpers aren't promise aware, though, as that has to be accounted for in user land.
