### ISSUE TITLE
Doesn't pass dependency lint

### ISSUE THREAD

**Issue by luketheobscure** [miguelcobain/ember-leaflet#171]
ember-leaflet lists `"ember-wormhole": "^0.5.2"` as a dependency. It also lists `ember-composability-tools` as a dependency, which lists `"ember-wormhole": "0.5.1"` as a dependency. This means that both versions 0.5.1 and 0.5.2 get installed.

**Solution**: Either drop the ember-leaflet wormhole dependency down to `^0.5.1`, or loosen the `ember-composability-tools` by adding the `^` (since I see you own both repos).

**Comment by miguelcobain** [comment]
This shouldn't be an issue anymore on latest versions since we don't depend on ember-wormhole anymore (and ember-composability-tools doesn't as well). 👍
