### ISSUE TITLE
Map container is moved to the front in leaflet v3.0.11 

### ISSUE THREAD

**Issue by figuedmundo** [miguelcobain/ember-leaflet#173]
Hi,

When I worked with version of leaflet 2.2.7, the map was in the back and the elements were displayed over the map like in the picture below, but in the version 3.0.11 the map is in the front.

![leaflet_old_new](https://user-images.githubusercontent.com/815466/29504464-eaa14430-860d-11e7-9894-5c1bf1f1e751.png)

Setting the z-index of the leaflet-container element to -1 the map is pushed to the back but the map is inaccessible, I  mean, the map cannot be zoom-in/out or the tooltip of the marker is not displayed when it is tapped.

In v3.0.11 the button element is like hidden, I mean when the tiles of the map are loading the button is visible (see picture below) but when the tiles are loaded the button disappears but if it's location is tapped the action related with the button is triggered. 

![tiles_loading](https://user-images.githubusercontent.com/815466/29504752-f2ee629c-860f-11e7-89d9-ade1117a740c.png)

**Comment by miguelcobain** [comment]
New leaflet versions set the z-index of .leaflet-pane to 400. Using `z-index: 401;` or greater on whatever you want to place over the map should work.
