### ISSUE TITLE
onDblclick not working

### ISSUE THREAD

**Issue by OlmoDalco** [miguelcobain/ember-leaflet#177]
Im trying to use an **onDblclick** action  as well as an onClick action on my map as documented over her: http://www.ember-leaflet.com/docs/leaflet-map

However, as soon as i add the onClick action to the map, the onDblick action is not called any longer. Instead i end up with the onClick action for click and dbClick.

Any suggestions how to fix it?

**Comment by devotox** [comment]
@OlmoDalco Can you add your code in here that you wrote for the Dblclick

some issues I had was that I wrote onDblClick instead of onDblclick or also I see in one of your instances of OnDbclick you actually just wrote onDblick.

**Comment by miguelcobain** [comment]
Probably a typo. Please reopen if still an issue.
