### ISSUE TITLE
feature group

### ISSUE THREAD

**Issue by drewda** [miguelcobain/ember-leaflet#18]
Have you considered adding support for [L.featureGroup](http://leafletjs.com/reference.html#featuregroup)? It would help for hiding/showing larger numbers of features, and also calculating `getBounds()` on multiple features.

**Comment by miguelcobain** [comment]
@drewda Can you provide me a concrete use case?

What are you using to show/hide layers?

**Comment by drewda** [comment]
When I've previously used Backbone to wrap Leaflet features and feature groups, I'd have a Backbone view wrap the feature group, in order to be able to toggle visibility of the group as a layer and to allow users to zoom in to the extents of each layer.

For example: a bunch of bus stops as markers in one feature group/layer, a bunch of route polylines as geometries in another feature group/layer, and Census polygons as geometries in another feature group/layer.

Not sure how this would fit into the data-down, actions-up paradigm

**Comment by miguelcobain** [comment]
> When I've previously used Backbone to wrap Leaflet features and feature groups, I'd have a Backbone view wrap the feature group, in order to be able to **toggle visibility** of the group as a layer and to allow users to zoom in to the extents of each layer.

What I was asking was how were you toggling visibility of layers. Where you using leaflet's included layer control? http://leafletjs.com/reference.html#control-layers

**Comment by drewda** [comment]
When using Backbone (or another library to wrap views), I generally prefer to create my own controls for toggling layer visibility that live outside of the map div.

**Comment by miguelcobain** [comment]
> I generally prefer to create my own controls for toggling layer visibility that live outside of the map div

This is my point. I've never needed feature group to toggle layer visibility. I just use normal ember templates. Example:
```hbs
{{#if poisVisible}}
  {{#each pois as |poi|}}
    {{marker-layer lat=poi.lat lng=poi.lng}}
  {{/each}}
{{/if}}
```
When `poisVisible` is `false`, the markers are removed/not added to the map.

Regarding the bounds issue, I normally use an ember computed property. Example:
```js
poiBounds: Ember.computed('pois.[]', function() {
  let poiLocations = this.get('pois').mapBy('location');
  return L.latLngBounds(poiLocations);
})
```

Let me know if this solves your issues.

**Comment by drewda** [comment]
That's great--and addresses both of my issues. Thank you.

Worth including a few of these as examples in the docs, for others who are still learning how to use the Ember approach to Leaflet?

**Comment by miguelcobain** [comment]
I'm thinking of adding a "cookbook" section on the website. These could be some recipes. The website is based on ember-power-select.com
I accept PR's with such a section.

**Comment by drewda** [comment]
Sounds like good additions to a "cookbook." When I have spare time, I'll be glad to contribute.
