### ISSUE TITLE
GeoJSON style options cleared

### ISSUE THREAD

**Issue by alkamin** [miguelcobain/ember-leaflet#180]
It seems that setting style options on a `geojson-layer` (`color` in my case) via a computed property is cleared by the `pushDataToLeaflet` function in `geojson-layer.js`: 

https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/geojson-layer.js#L34

Stepping through with a debugger from the style mixin (here specifically: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/mixins/style.js#L28) allows me to see the new color being applied to the geojson, and then let's me see that when the layers are cleared (`this._layers.clearLayers` in `geojson-layer.js`) the style options are not re-applied.

**Comment by alkamin** [comment]
I'm thinking this may be a result of using the geoJSON's properties to compute the `color` so that the result is the style observer adding the style and then the updated geoJSON attribute causes that style to be cleared.

**Comment by alkamin** [comment]
I did some further testing and this appears to happen whether or not the `geoJSON` is updated or not.

**Comment by miguelcobain** [comment]
This should be fixed on master. Please reopen if still an issue.
