### ISSUE TITLE
style property in geoJSON layer not bound

### ISSUE THREAD

**Issue by gschulze** [miguelcobain/ember-leaflet#181]
While individual style properties of the geoJSON layer are bound, the `style` property as a whole is not.
Leaflet allows to pass a function as style property, which can be used to style individual features based on their properties. It would be nice to be able to change that function later on and having the layer reflecting the change.

**Comment by miguelcobain** [comment]
Adding `style` as a `leafletProperties` did the trick. Also added a test for it.
