### ISSUE TITLE
Could not find module `@ember/utils`

### ISSUE THREAD

**Issue by benjaminlong** [miguelcobain/ember-leaflet#189]
Hello !

I am new with `ember-leaflet` and I'm sorry about this pretty stupid question. I'm trying to add the addon to my app.  However I got this error:

`Error: Could not find module '@ember/utils' imported from 'my-app/initializers/leaflet-assets'`

I'm using:
- ember-leaflet: 3.0.13,
- ember-cli: 2.17.0,
- ember-data: 2.14.0,
- ember-cli-fastboot: 1.1.2

Any idea why ?

**Comment by benjaminlong** [comment]
Sorry for disturbing the community, just needed to upgrade my dependencies.

**Comment by arnaudbesnier** [comment]
Hey @benjaminlong, I am facing the same issue on Ember app launch (after successful addon installation)
What do you mean exactly by "upgrade my dependencies"?

**Comment by benjaminlong** [comment]
I updated my dependencies, mainly `ember-cli-*` if I remember properly.  Which versions are you using ?

**Comment by arnaudbesnier** [comment]
I eventually manage to use the package with version 3.0.12.
I also had the issue with v3.0.13.

I am using `ember-cli` 2.12.2.
