### ISSUE TITLE
Cleanest way to keep one polyline on top of others (but under markers)?

### ISSUE THREAD

**Issue by mjanda** [miguelcobain/ember-leaflet#19]
Can you point me in the right direction? I'm thinking in several directions, but nothing what I would consider elegant solution.

**Comment by miguelcobain** [comment]
After reading https://github.com/Leaflet/Leaflet/issues/185, this seems to be a svg limitation. 

Can you control the order in which you render your polylines?

**Comment by mjanda** [comment]
Well, I'm hiding and showing one of them and I want to keep it at the bottom (I want to highlight part of other polyline that way), so I can't.

**Comment by miguelcobain** [comment]
@mjanda The best way should be extending polyline and call method `bringToFront` on the leaflet layer. http://leafletjs.com/reference.html#path-bringtofront

Example:
```js
// app/components/front-polyline-layer.js
import PolylineLayer from 'ember-leaflet/components/polyline-layer';

export default PolylineLayer.extend({
  didCreateLayer() {
    this._layer.bringToFront();
  }
})
```

Alternatively, if you don't want to extend a component, you can create an `onAdd` action and call `bringToFront()` there (probably easier).

Keep in mind that this will bring your layer to the front of *all* path layers.

**Comment by mjanda** [comment]
Thank you, works great.
