### ISSUE TITLE
Fix for 'cannot read property removeEventListener of null' error

### ISSUE THREAD

**Issue by Techn1x** [miguelcobain/ember-leaflet#195]
Hi all,

I am using ember-leaflet + ember-leaflet-layer-control
I have the following code in my leaflet map template
```handlebars
{{!-- Geofences --}}
{{#layer-group name="Geofences" default=true}}
  {{#each geofences as |fence|}}
    {{#geojson-layer geoJSON=fence color='red'}}
      {{#tooltip-layer permanent=false}}
        Some tooltip content..
      {{/tooltip-layer}}			
    {{/geojson-layer}}
  {{/each}}
{{/layer-group}}
```

If I untick the Geofences layer in the layer control, the geofences correctly disappear from the map. If I then navigate away from my map page, I end up with the following error
![error](https://user-images.githubusercontent.com/1049837/38476836-3a1d3eba-3bf3-11e8-9560-24d1cd7ba13e.png)

The way I fixed this was overriding the tooltip-layer.js in the following way (just added a defensive check for whether _map is defined for the layer);
```javascript
//app/components/leaflet/tooltip-layer-fixed.js
import TooltipLayer from 'ember-leaflet/components/tooltip-layer';
export default TooltipLayer.extend({
  _removePopupListeners() {
    let parentComponent = this.get('parentComponent');
    if(parentComponent._layer._map) {
      parentComponent._layer._map.removeEventListener('layerremove', this._onLayerRemove, this);
    }
  }
})
```

It only happens for the geofences layer (and not my other overlay layers), because the geofences layer has tooltips. I also tried a polygon-layer instead of a geojson-layer and the error still occured. I think this is an issue with ember-leaflet and not the layer control addon, but please let me know if I should report this on that addon's github instead.

**Comment by Techn1x** [comment]
I would submit a PR but my last PR from months ago is yet to be actioned or replied to, so I've just posted this code here for others in the same situation as me.

**Comment by plcarmel** [comment]
See https://github.com/miguelcobain/ember-leaflet/pull/160

**Comment by miguelcobain** [comment]
This shouldn't be an issue anymore on master. Please reopen if this still persists.

**Comment by Techn1x** [comment]
Confirmed fixed, cheers
