### ISSUE TITLE
GeoJSON layers

### ISSUE THREAD

**Issue by drewda** [miguelcobain/ember-leaflet#2]
Any thought of adding support for GeoJSON layers?

**Comment by miguelcobain** [comment]
@drewda I think that could be done easily.

However, I've never really been a fan of the idea. 
Leaflet geojson layers merely delegates layer creation to other layers.
I always think of geojson as a data concern, not something a view layer should care about. However, I see that pragmatism is sometimes important.

Do you mind illustrating your use case, even if it appears very simple?

**Comment by radcliff** [comment]
It is nice to be able to pass GeoJSON directly to the map and get a layer, as Leaflet is set up to read from the GeoJSON data directly as it is widely used. Actually, what is a better way of loading GeoJSON data onto a Leaflet map other than a GeoJSON layer?

**Comment by miguelcobain** [comment]
@radcliff @drewda My data always ends up in controllers using ember data models, mainly.
So, I have a serializer that builds my model from geojson. Then, I create leaflet layers normally using ember-leaflet and templates, like in the examples.

I guess that sometimes you just want to pass in some geoJSON to display something read-only. Be aware that there will be no bound properties other than "style" properties.

I'll mark this as a todo, then. :+1:

**Comment by drewda** [comment]
Thanks for adding this to the list, @miguelcobain!

There are often situations where my colleagues and I load up GeoJSON from an API endpoint or from a local file and add it as another map layer. It's not necessary to manipulate the individual geometries within the GeoJSON layer--just to add/remove/hide/show the layers.

Perhaps down the line, after adding simple GeoJSON layers, there would also be a way for you to share your GeoJSON-to-Ember-Data-model serializer? That sounds useful.

**Comment by radcliff** [comment]
>My data always ends up in controllers using ember data models, mainly.

I noticed that ember-leaflet uses controllers heavily, but I thought that controllers were going away soon, in an upcoming version of Ember. Have you thought about what ember-leaflet might look like when that happens?

**Comment by miguelcobain** [comment]
There seems to be a lot of people with that concern. However, have no fear, my friend. 

Please read this article:
http://locks.svbtle.com/controllers-are-dead-long-life-controllers

**Comment by miguelcobain** [comment]
@drewda @radcliff `{{geojson-layer` was released on `2.2.1`.

Closed by https://github.com/miguelcobain/ember-leaflet/pull/44

**Comment by drewda** [comment]
Thanks, @miguelcobain and @ForSpareParts!
