### ISSUE TITLE
New addon: wrapper for MultiOptionsPolyline

### ISSUE THREAD

**Issue by mjanda** [miguelcobain/ember-leaflet#20]
It's my first ember addon / npm package etc., so I hope I didn't make some newbie mistake :-) But it works for me...

https://www.npmjs.com/package/ember-leaflet-multi-options-polyline

**Comment by miguelcobain** [comment]
Awesome job! Congrats on your first addon!
It looks good to me.

Want to make a PR that adds it to the list?
www.ember-leaflet.com is just a regular ember. It's located at `tests/dummy` directory of this repo.

**Comment by miguelcobain** [comment]
Specifically this file: https://github.com/miguelcobain/ember-leaflet/blob/master/tests/dummy/app/templates/addons.hbs

**Comment by mjanda** [comment]
Ok, I'll send it tomorrow.
