### ISSUE TITLE
how to change attribution

### ISSUE THREAD

**Issue by Pingu69** [miguelcobain/ember-leaflet#253]
How can I change the attribution of the map? I tried passing string to attribution property, but it doesn't work.

`{{#leaflet-map lat=lat lng=lon onLoad=(action (mut map)) zoomControl=true scrollWheelZoom=false attribution="attribution" zoom=15 bounds=bounds as |layers|}}`

**Comment by miguelcobain** [comment]
@Pingu69 usually the `attribution` should be set on the tile layer and not on the map. Can you try that and report back, please?

**Comment by Pingu69** [comment]
> @Pingu69 usually the `attribution` should be set on the tile layer and not on the map. Can you try that and report back, please?

Thanks for the help! I put the attribution property in the tile layer and passed a string, and it works!
