### ISSUE TITLE
Using fitBounds

### ISSUE THREAD

**Issue by lucacorti** [miguelcobain/ember-leaflet#26]
I'm using a computed property to center the map on bounds calculeted from the set of markers added to the map:

```
  bounds: Ember.computed('places', function(){
    return L.latLngBounds(this.get('places').map(function(place){ return place.get('location'); }));
  })
```

This works but not on the initial page load. On the first page load the map, the map is not zoomed. The set of markers is set on the controller from the route.

**Comment by miguelcobain** [comment]
@lucacorti What does your template look like?

**Comment by lucacorti** [comment]
```
  {{#leaflet-map bounds=bounds scrollWheelZoom=false}}
    {{tile-layer url=mapUrl attribution=attribution}}
    {{#each events as |event|}}
      {{#marker-layer location=event.location icon=event.icon}}
         ...
      {{/marker-layer}}
    {{/each}}
  {{/leaflet-map}}
```

**Comment by miguelcobain** [comment]
Do your pages.location get changed during the load? (caused by, for example, async relationships)

If you do this, how many logs to you see in a a single page load:
```js
bounds: Ember.computed('places', function(){
  console.log(this.get('places').map(p => p.get('location')));
  return L.latLngBounds(this.get('places').map(function(place){ return place.get('location'); }));
})
```

**Comment by lucacorti** [comment]
I have two cases, in one `location` is a computed property on the model. In the other, location is a computed property on the same property through a relationship which is not declared async and is sideloaded via JSONAPI in the route. In both cases, I see only one log line with the array of locations.

**Comment by miguelcobain** [comment]
This is the line that sets the bounds: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/leaflet-map.js#L88

Can you break point there and make sure that `this.get('bounds')` has the expected value?
Also, if places is an array, your computed probably should look like `Ember.computed('places.[]', function() {.

I'm running out of ideas. :/

**Comment by lucacorti** [comment]
Yes, `fitBounds` is called exactely once and this.get('bounds') returns what seems the correct value to me.

**Comment by miguelcobain** [comment]
> This works but not on the initial page load. On the first page load the map, the map is not zoomed. The set of markers is set on the controller from the route.

Can you somehow record this happening? Maybe if I see it I can understand what is happening.

**Comment by lucacorti** [comment]
Here you go: http://recordit.co/uhtuH9zJfh

I Initially refresh the page a couple times. As you can see the map is not zoomed correctly. Then I transition to a different route, where the map is correctly zoomed, and click back to the original one, which is now correctly zoomed too.

**Comment by miguelcobain** [comment]
@lucacorti I'm pretty confident that the bounds must be incorrectly computed initially.

Can you show me the `location` computed property on the model? I believe that `location` initially isn't correct because the computed that depends on a relationship.

Also, try changing the bounds computed to `Ember.computed('places.@each.location', function() {`.

**Comment by lucacorti** [comment]
Using `'places.@each.location'` has no effect. This is the relevant part of the model:

```
...
latitude: DS.attr('number'),
longitude: DS.attr('number'),
location: Ember.computed('latitude', 'longitude', function() {
    var latitude = this.get('latitude');
    var longitude = this.get('longitude');
    return L.latLng(latitude, longitude);
}),
...
```

**Comment by miguelcobain** [comment]
> In the other, location is a computed property on the same property through a relationship which is not declared async and is sideloaded via JSONAPI in the route.

What about this one? Or isn't it used in this faulty map instance?

**Comment by lucacorti** [comment]
Both behave the same, the other one just retrieves the property from the relationship:

```
  location: Ember.computed('place', 'parent', function() {
    let place = this.get('place');
    let parent = this.get('parent');

    if(place) {
      return place.get('location');
    }

    if (parent) {
      return parent.get('place').get('location');
    }
  }),
```

**Comment by miguelcobain** [comment]
Try changing it to:
```js
  location: Ember.computed('place.location', 'parent.place.location', function() {
    let place = this.get('place');
    let parent = this.get('parent');

    if(place) {
      return place.get('location');
    }

    if (parent) {
      return parent.get('place').get('location');
    }
  }),
```
while keeping the previous `Ember.computed('places.@each.location', function() {.`

tip, you can just do:
```js
  location: Ember.computed.or('place.location', 'parent.place.location')
```
and crush 12 lines of code into 1. :)

**Comment by lucacorti** [comment]
Nice :)

Still no go though.

**Comment by miguelcobain** [comment]
@lucacorti I'm officially out of ideas.

Since I can't reproduce that problem here, I think right now we have two options:

1. you provide a failing test that reproduces this issue and I'll try to make it pass
2. you provide a repository that reproduces your problem and I try to solve it from there as well

since I can't have a starting point, it's hard for me to solve it. :/

**Comment by lucacorti** [comment]
Sure, I'm doing some more debugging, I'll let you know what I find or I'll provide code.
Thanks for you time :)

**Comment by miguelcobain** [comment]
@lucacorti that problem was that you were including the styles in the `tsc.hbs` template with this line:
`<link rel="stylesheet" href="/assets/thats.css">`.

This means that, at the time of rendering, leaflet doesn't know the container size. So, `fitBounds` doesn't really make sense when we don't know the container size, right? Like, "fit" where?

Placing the style `<link` in <head> at index.html file solved the problem.

Glad to see ember-leaflet is helping art in some way! :+1:

**Comment by lucacorti** [comment]
Thanks, that's an hack I was trying to merge two different layouts in a single ember project without reworking the CSS.

Yay for art ;)
