### ISSUE TITLE
ember-cli-babel@7 cannot be used by ember-cli versions older than 2.13, you used 2.6.2

### ISSUE THREAD

**Issue by mikeelemuel** [miguelcobain/ember-leaflet#285]
I was trying to install this addon by running the command `ember install ember-leaflet` but I received an error called

ember-cli-babel@7 (used by ember-leaflet at /Users/insetPathHere/node_modules/ember-leaflet) cannot be used by ember-cli versions older than 2.13, you used 2.6.2

Ember and babel version that I am using are

    "ember-cli": "2.6.2",
    "ember-cli-babel": "^5.1.6",

Node version is `v8.11.3`

**Comment by miguelcobain** [comment]
You're using a really old version of ember-cli.
Is upgrading your ember and ember-cli versions not possible for you for some reason?

**Comment by mikeelemuel** [comment]
Hi @miguelcobain , thank you for getting back to me. As of now, it is not possible yet. There are some other addons that are associated with the current ember-cli version that I am using.

**Comment by miguelcobain** [comment]
you can try to use ember-leaflet v3.0.17, which is the most recent version that uses ember-cli-babel 6.x.

Try installing it with `ember install ember-leaflet@3.0.17`

**Comment by mikeelemuel** [comment]
Let me try it

**Comment by mikeelemuel** [comment]
Didn't receive any error with the version you've suggested. :D 👍
