### ISSUE TITLE
Adding custom icons is broken

### ISSUE THREAD

**Issue by Suven** [miguelcobain/ember-leaflet#31]
Hey!

I am not able to use custom icons in `marker-layer` due to a changed leaflet-api.

Demo-Code

    {{#marker-layer location=marker.location icon=marker.icon}}marker.text{{/marker-layer}}

See this issues for more infos: https://github.com/Leaflet/Leaflet/issues/534

It really does not matter what the contents of `marker.icon` are, you'll always receive

    TypeError: options.icon.createIcon is not a function. (In 'options.icon.createIcon(this._icon)', 'options.icon.createIcon' is undefined)

The auto-fetched version of leaflet during ember install was `~0.7.7`

**Comment by miguelcobain** [comment]
@Suven what is the value of `marker.icon`? It should be set to an instance of `L.icon`.

**Comment by Suven** [comment]
Oh. Sorry about that.. I was under the wrong impression that this would have been abstracted by the addon.

It works like you suggested

**Comment by miguelcobain** [comment]
@Suven any idea of how we could abstract it?

**Comment by Suven** [comment]
I think leaflet is overcomplicating things with their options for size, a separate retina-graphic and so on.

I would suggest to just give an url as icon-parameter and pass that to the constructor. If you additionally support a class-parameter, the rest could be done via CSS anyway.

Maybe it's a good idea to add this as a different attribute to the component to not break existing apps, or apps which still might want to configure the shadow and stuff?

**Comment by miguelcobain** [comment]
This gave me an idea. We could have some helpers to quickly create icons and such things. Example:

```hbs
{{#marker-layer icon=(icon "marker.png")}}
  Marker popup
{{/marker-layer}}
```

Similar helpers could be created for div icons and even latlngs `location=(latlng model.latitude model.longitude)`.

**Comment by Suven** [comment]
Sounds great! Would love it.

I'm currently working on stuff around this plugin anyway. If you like to, I can also make a PR-Proposal

**Comment by miguelcobain** [comment]
I'd like to list exactly how the helpers would work and their api's. 
I'm a bit worried if bindings would work. 

```hbs
{{#marker-layer icon=(icon iconUrl)}}
  Marker popup
{{/marker-layer}}
```

Changing `iconUrl` would change the icon as well?  Not entirely sure of how helpers work at this level.

**Comment by miguelcobain** [comment]
Update: helpers are bound normally. Twiddle: https://ember-twiddle.com/82260a36dc9d28f9f434?openFiles=application.template.hbs%2Cmy-component.template.hbs

This feature could be very easy to do.

**Comment by bloodknight2010** [comment]
This is my codes.
```
{{#each shopModel as |shop|}}
          {{#marker-layer icon=(icon '/icons/owner.png') location=shop.position as |marker|}}
          {{/marker-layer}}
{{/each}}
```
I got the following error.
 **iconUrl not set in Icon options**
How to slove?
 Pls help me.

**Comment by bloodknight2010** [comment]
I got the solution following sample codes.
```
{{marker-layer
  location=loc
  icon=(icon
    iconUrl="my-icon.png"
    iconRetinaUrl="my-icon@2x.png"
    iconSize=(point 38 95)
    iconAnchor=(point 22 94)
    popupAnchor=(point -3 -76)
    shadowUrl="my-icon-shadow.png"
    shadowRetinaUrl="my-icon-shadow@2x.png"
    shadowSize=(point 68 95)
    shadowAnchor=(point 22 94)
});
```
