### ISSUE TITLE
Path error in template layout call using octane blueprint

### ISSUE THREAD

**Issue by gilles-bertrand** [miguelcobain/ember-leaflet#316]
Hi, in the last version when you use the component, we receive this error 

> Error: Could not find module `ember-leaflet/templates/leaflet-map` imported from `ember-leaflet/components/leaflet-map`
> 

To correct this I had to change the line 10 of the components/leaflet-map.js to take the current in path

**Comment by miguelcobain** [comment]
@gilles-bertrand what ember-cli version are you using?
Are you using ember octane blueprint?

**Comment by gilles-bertrand** [comment]
@miguelcobain yes indeed do I need to do somthing specific

**Comment by miguelcobain** [comment]
As far as I can tell this is a bug on that ember-cli version.
I had to use the latest released ember-cli version and it worked fine.

**Comment by miguelcobain** [comment]
It might be worth to create an issue in ember-cli's repo.

**Comment by gilles-bertrand** [comment]
Ok Ill try to update ember cli to the new version 

> TypeError: func is not a function

> 
Any idea why ?

**Comment by miguelcobain** [comment]
@gilles-bertrand i specified `"ember-cli": "3.8.3"` in my package.json, and it worked.

Didn't try with later versions. :(

**Comment by backspace** [comment]
There’s some discussion of this problem [here](https://github.com/ember-cli/ember-cli/issues/8693).

**Comment by jelhan** [comment]
Ember CLI 3.13.0 was released without a bug fix. Ember Leaflet is currently broken on Ember CLI 3.13. Ember Bootstrap was also affected by this bug. This is the fix we landed there: https://github.com/kaliber5/ember-bootstrap/pull/883 It's not beautiful but it seems to work quite stable.

**Comment by nummi** [comment]
Still seeing this in `3.14.0-beta.2`.

**Comment by m3l1x** [comment]
@miguelcobain do you consider to merge @backspace 's PR #342?

**Comment by nummi** [comment]
> Please note that this is only blocking Ember CLI upgrade. You can use ember-source@~3.14.0 with all it's amazing Octane features together with ember-cli@~3.12.0

Unfortunately this did not work for me. Setting `"ember-cli": "3.12.0"`. No errors in the CLI or browser console — nothing renders. Probably something specific with my app.

**Comment by miguelcobain** [comment]
Should be fixed in ember-leaflet 4.0.0
