### ISSUE TITLE
`ember-invoke-action` isn't automatically installed

### ISSUE THREAD

**Issue by mdebbar** [miguelcobain/ember-leaflet#32]
When I followed the docs and installed `ember-leaflet`, I got the error:
> Could not find module `ember-invoke-action` imported from `ember-leaflet/components/base-layer`

The problem is that the dependency `ember-invoke-action` doesn't get installed automatically. I'm not too familiar with Ember, but I think that should be done in the blueprint?

**Comment by miguelcobain** [comment]
Ah, we should move that to `dependencies` and not `devDependencies`. That way the dependency gets installed.

**Comment by mdebbar** [comment]
It's already in `dependencies`.

**Comment by miguelcobain** [comment]
@mdebbar 

So, to recap:

```bash
$ ember new my-app
$ cd my-app
$ ember install ember-leaflet
$ ember s
```

results in 
> Could not find module ember-invoke-action imported from ember-leaflet/components/base-layer

?

**Comment by miguelcobain** [comment]
Closing for the lack of feedback.
