### ISSUE TITLE
How to get a reference to the leaflet map?

### ISSUE THREAD

**Issue by mdebbar** [miguelcobain/ember-leaflet#35]
In some cases, we need to have a reference to the map to call some leaflet functions. Is there an easy way to access the map?

There are several use cases:
- If the url doesn't have the `lat` and `lng` params, we need to call `map.fitBounds(...)` based on the current data.
- We need to support drawing on the map using `leaflet.draw` which requires a reference of the `map`.
- We have a custom `zoom` class that we need to add to the map: `CustomZoom(...).addTo(map)`.
- We need to add a scale to the map using `L.control.scale(...).addTo(map)`

**Comment by mdebbar** [comment]
Extending `LeafletMap` would be one solution but I couldn't get it to work.

**Comment by mdebbar** [comment]
Ok now I'm able to extend `LeafletMap` and make it work. But I still prefer if those use cases can be done with composition instead of inheritance.

**Comment by miguelcobain** [comment]
@mdebbar you can do two things:

1. Use inheritance, like you've said
2. Use the `onload` map action. The action is called with the original leaflet event passed in. From that event you can access the leaflet map instance.

**Comment by miguelcobain** [comment]
Also, this discussion might be helpful: https://github.com/miguelcobain/ember-leaflet/issues/11

**Comment by allthesignals** [comment]
This is really hard to do for some reason... I made a custom leaflet-map component, and I'm trying to get the map instance so I can re-position the zoom control (which is really easy to do in leaflet vanilla). The discussion seems to imply that I'd need to define an action in the parent controller to do component logic, which seems awkward. Is there no way to do this from the component itself? Or do you think this is better design? Sorry if this discussion is already somewhere else...

**Comment by miguelcobain** [comment]
@allthesignals if you prefer, you can override the leaflet map component and access the raw leaflet map instance using `this._layer` in a `didCreateLayer` method (don't forget to call `this._super(...arguments);`.
