### ISSUE TITLE
Open popup for marker layer by default

### ISSUE THREAD

**Issue by ianpetzer** [miguelcobain/ember-leaflet#37]
Hi there,

Thanks for this amazing library. We've upated from version 1 (gabesmed) and we've taken advantage of the maker layer to create some beautiful popups for our marker layers.  

I would like have one of these popups open by default when the map is created but I'm struggling to figure out how to do it.

Is there a way to do this?
Thanks!

**Comment by miguelcobain** [comment]
Hi. Glad you're enjoying it. :) 

If you create the marker layer with `popupOpen=true`, does it meet your requirements?

**Comment by ianpetzer** [comment]
Hi Miguel,

Thanks for the speedy reply.

That option works perfectly for me. Thanks!

**Comment by ianpetzer** [comment]
I'll close this issue since I'm all sorted
