### ISSUE TITLE
Marker Icons don't work with ember 2.4

### ISSUE THREAD

**Issue by andreabettich** [miguelcobain/ember-leaflet#38]
I just started a new project with ember 2.4 and ember-leaflet and I'm having problems getting the marker icons to work.

I created a new ember 2.4 project with just an example in it and it also doesn't work.
[Test Project Ember 2.4 and ember-leaflet](https://github.com/andreabettich/ember-leaflet-test)

```bash
 ember -v
version: 2.4.0
node: 5.5.0
os: linux x64
```

The md5 hash of the icons are not the same which is also strange and maybe can help you find the problem.
`87f6ca46ac356e81dc438589630ae107  bower_components/leaflet/dist/images/marker-icon.png`
`d95f8980883dd995b4a9595825bf8366  dist/assets/images/marker-icon.png`

**Comment by borisrorsvort** [comment]
Glad I'm not the only one. :+1:

**Comment by iambenjohnson** [comment]
I am also having this problem using Ember 2.4.0 and 2.4.1. One thing I don't understand is that [in the website](http://www.ember-leaflet.com/docs/adding-layers), why do the JavaScript snippets say `export default Ember.Controller.extend` whereas if the map was built as a component (like the example posted  by @andreabettich above) it should say `export default Ember.Component.extend`.

**Comment by miguelcobain** [comment]
@iambenjohnson as you said very well "**if** the map was built as a component". :smile: 

You can use `{{#leaflet-map` component in a controller's template, in a component's template or you can even subclass the LeafletMapComponent. None of this is ember-leaflet specific. This is true for any ember component.

@andreabettich @borisrorsvort @iambenjohnson When you say "marker icons don't work" you mean the deafult icons? No custom icons at all? That's bad news.

No errors? Anything?

**Comment by borisrorsvort** [comment]
![image](https://cloud.githubusercontent.com/assets/39081/13630976/7dc97e30-e5e2-11e5-9ba5-2cd29a0f00bf.png)

**Comment by borisrorsvort** [comment]
For a a custom icon. Default works well :smile:

**Comment by miguelcobain** [comment]
@borisrorsvort how are you defining the custom icon?

**Comment by borisrorsvort** [comment]
![image](https://cloud.githubusercontent.com/assets/39081/13632303/4debdbc0-e5e9-11e5-9c5c-de8e908d72d3.png)
![image](https://cloud.githubusercontent.com/assets/39081/13632319/5f5bf0ca-e5e9-11e5-9da0-f0e510658f3d.png)

**Comment by miguelcobain** [comment]
The test project from @andreabettich doesn't have any custom icons.

I've updated ember-leaflet project to latest ember and ember-cli.
You can see the demo live at www.ember-leaflet.com

That proves that default marker icons work, @andreabettich

**Comment by miguelcobain** [comment]
@borisrorsvort that won't work.

When you do `icon=userCustomIcon` you're actually saying that the `icon` property **is a function**. `userCustomIcon` is a function, if you take a closer look.

You can solve this by making `userCustomIcon` the icon directly:
```js
userCustomIcon: L.icon({
  iconUrl: '...'
  // etc
})
```

or, if you need a more complex icon, you can just use a computed property:

```js
userCustomIcon: computed(function() {
  let fancyIconUrl = this.get('someService'). get('whatever');
  return L.icon({
    iconUrl: fancyIconUrl
    // etc
  });
})
```

**Comment by miguelcobain** [comment]
I will close this until further developments. Feel free to comment anyway.

**Comment by borisrorsvort** [comment]
Yep thank that work. I'm not the only one who did that mistake. Maybe its a good idea to put an example in the docs :smile: 
Thanks for the help and the lib nonetheless :+1:

**Comment by miguelcobain** [comment]
Here is an attempt of making custom icons even easier: https://github.com/miguelcobain/ember-leaflet/issues/33#issuecomment-185638004

**Comment by borisrorsvort** [comment]
:+1:

**Comment by miguelcobain** [comment]
@borisrorsvort check the new helpers that I published in 2.2.0: https://github.com/miguelcobain/ember-leaflet/issues/33#issuecomment-194247389

**Comment by iambenjohnson** [comment]
Thanks @miguelcobain. Your comments helped me get my templates working.

**Comment by borisrorsvort** [comment]
@miguelcobain :dancers:  Nice :)
