### ISSUE TITLE
Accessing Leaflet methods

### ISSUE THREAD

**Issue by kmmathis** [miguelcobain/ember-leaflet#39]
What is the prescribed way for calling leaflet's methods like getBounds or getCenter? In a non-Ember environment I would have the map stored in a variable and call the methods that way, but I'm still a little confused on where the map object is stored when it's an Ember component.

**Comment by localyost** [comment]
Hi kmmathis,
I'm not quite sure if this is what you're looking for but I've done this in for my apps:
Whenever I initialize a map in the template, I use the `onLoad()` method to then set a property in my controller.

in your template handlebars set a function to be called upon loading the map

```
{{#leaflet-map ... onLoad="getMap"}}
...
{{leaflet-map}}
```
and then in the controller declare the getMap action:

```
actions: {
    getMap: function(map){ 
       this.set('map', map.target);
     }
}
```
 then you can do something in the controller like: 
```
addMarker : function(){
   const map = this.get('map');
   L.marker(...).addTo(map) 	
}
```

hope this helps! The developers made these awesome [docs](http://www.ember-leaflet.com/docs/leaflet-map). they've really helped me!

**Comment by miguelcobain** [comment]
@localyost point a valid solution.

This is a duplicate question. Here is the other issue: https://github.com/miguelcobain/ember-leaflet/issues/35

I'd like to point out that the whole idea is to avoid to use leaflet directly. Some times you need to, but adding a marker like in @localyost's example doesn't seem a good usage of that.

> The developers made these awesome docs. they've really helped me!
Glad you liked it. :)

**Comment by localyost** [comment]
> I'd like to point out that the whole idea is to avoid to use leaflet directly. Some times you need to, but adding a marker like in @localyost's example doesn't seem a good usage of that.

this is **definitely ** true, sorry about that... I just used the first thing that came to my head :)
