### ISSUE TITLE
zoomOffset seems to break map

### ISSUE THREAD

**Issue by linearza** [miguelcobain/ember-leaflet#392]
Hi, in short, setting the `zoomOffset` to `-1` on the `<layers.tile>` breaks my map once I set the tile size to 512. Im using mapbox which has a zoom offset so the text appears very small, and this is the proposed fix.

My implementation is pretty standard:

```
<LeafletMap @minZoom={{minZoom}} @bounds={{bounds}} as |layers|>
    <layers.tile @url={{layersUrl}} @zoomOffset={{zoomOffset}} />
    ...
</LeafletMap>
```

Am i missing something obvious?

**Comment by miguelcobain** [comment]
What do you mean by "breaks my map"?
Are there any thrown errors?
Is it just visually broken?

**Comment by linearza** [comment]
Ah, just posted screenshots to the #e-leaflet channel. Visually broken, no errors.
