### ISSUE TITLE
Adding custom control example

### ISSUE THREAD

**Issue by franktcurran** [miguelcobain/ember-leaflet#4]
I'm giving this addon a try and adding a map was very easy to do. However, I'm pretty new to ember, and I was hoping someone could provide an example of the best way to add a control to a leaflet-map.

Thanks!

**Comment by miguelcobain** [comment]
@franktcurran Welcome to Ember!

What kind of control do you want to add in your map?

**Comment by franktcurran** [comment]
@miguelcobain Thanks!
A lot of the map tile providers out there also provide services that let you search for a location, providing some sort of autocomplete/typeahead functionality for potential matches, and return a normalized address (for example, google's Places API). I'd like to add a search control like this to the map and then be able to use the selected result for further processing in my app.
Does this make sense?
Thanks again!

**Comment by miguelcobain** [comment]
@franktcurran My advice is that you build such a control in Ember.
I'm doing it in my production app, and it is far more maintainable.

Basically use something like the ember-power-select add-on (or build your own thing). Use that to search a list using some places API service.
Then, in the select action, you can just `this.set('center', place.someCoordinates);` and the map will center on those coordinates, if it is bound to the `center` property.

**Comment by franktcurran** [comment]
@miguelcobain, my question might not have been very clear, or I might just be very dense, or both. What I was wondering about was not how to make the control itself (although, I'll struggle with that as well), but how to add it to the map, so that it could be positioned like any of the other default controls. Looking at leaflet docs, http://leafletjs.com/reference.html#icontrol, I can go about doing this by making my customer control extend IControl and doing something like map.add(mycontrol) or mycontrol.addTo(map). I was wondering, with this addon, was there, or will there be, an expected way/pattern for going about this?

**Comment by miguelcobain** [comment]
@franktcurran 
you have two options for building leaflet controls:

1. The preferred one is to use ember to do that. You can see in the examples that I've used checkboxes and inputs to control layer insertion and removal. You can easily implement a control similar [to this one](http://leafletjs.com/examples/layers-control.html) with ember alone.
2. Sometimes we need leaflet controls, either by convenience or because of a leaflet plugin, etc. That is also very easy. Example using the plugin [leaflet locate control](https://github.com/domoritz/leaflet-locatecontrol):

```js
// app/components/leaflet-map.js
import LeafletMapComponent from 'ember-leaflet/components/leaflet-map';

export default LeafletMapComponent.extend({
  //hook that is called after the leaflet layer was created at `this._layer`
  didCreateLayer() {
    this._super(...arguments);
    //here, do whatever you need to do with `this._layer`
    this.L.control.locate().addTo(this._layer);
  }
});
```

**Comment by adhithyaraja** [comment]
Hi, I'm new to ember.
lmap.on('dragend', function(){
			var bounds = lmap.getBounds();
	});
I want achieve the same using ember-leaflet addon. In the addon map container controls are not with me. 
My template
{{#leaflet-map  lat=centerLocation.latitude lng=centerLocation.longitude zoom=6 }}
          {{tile-layer url=tileurl}}
   {{/leaflet-map}}
thanks in advance

**Comment by miguelcobain** [comment]
@adhithyaraja please wrap your code in ```.
Also, you should open a new issue next time, please.

You want to obtain the bounds of your map, correct?

```hbs
{{#leaflet-map lat=centerLocation.latitude lng=centerLocation.longitude zoom=6 onMoveend=(action "anActionInYourController")}}
  {{tile-layer url=tileurl}}
{{/leaflet-map}}
```
```js
export default Ember.Controller.extend({
  actions: {
    anActionInYourController(ev) {
      //ev is a raw leaflet event. see docs for more info
      //event sender is always at ev.target
      let bounds = ev.target.getBounds();
    }
  }
});
```

**Comment by adhithyaraja** [comment]
@miguelcobain Thanks. My doubt was similar to this. So I continued in this.
Your code worked for me. In the code, I got only the control of that particular event (onMoveEnd) . But my first doubt was How do I get the map(this.L) to my route? 
If you ask , why I want map control in route. I'm have to add third party map api layers in the basic layer map and that's where I'm in need of map control globally.

**Comment by miguelcobain** [comment]
> But my first doubt was How do I get the map(this.L) to my route?

Sorry, I didn't understand this question. What is `map(this.L)`? Try to rephrase your question, please.

> If you ask , why I want map control in route. I'm have to add third party map api layers in the basic layer map and that's where I'm in need of map control globally. 

You mean you need 3rd party tile layers? That is explained in the docs. Just use the `tile-layer` componente.

**Comment by borisrorsvort** [comment]
@miguelcobain I tried the previous snippet in leaflet-map :

```
  didCreateLayer() {
    this._super(...arguments);
    //here, do whatever you need to do with `this._layer`
    //use `this.L` to avoid global usage
    this.L.control.locate().addTo(this._layer);
  },

```
but I also get the error:

`this.L.control.locate is not a function`

ps:
Im using 1.0.0-rc.1 and "ember-leaflet": "ssured/ember-leaflet-1#leaflet-master" for compat with rc1 But I dont think the error has anything to do with the versionning since the method is in leaflet doc for a while.


Tell me if you need anything more to hep me. Thanks in advance

**Comment by miguelcobain** [comment]
@borisrorsvort have you added the leaflet plugin for that control?

**Comment by borisrorsvort** [comment]
@miguelcobain Ah sorry I thought the snippet was for the first solution my bad ^^
