### ISSUE TITLE
Map dimensions

### ISSUE THREAD

**Issue by borisrorsvort** [miguelcobain/ember-leaflet#41]
I was trying to bound map dimensions to window size using https://github.com/mike-north/ember-resize but apparently there is no way to bind styles attributes of the .leaflet-container directly. I know I could use jquery but I'd like to stay way from it if possible.

Do you have a solution in mind ?

**Comment by miguelcobain** [comment]
@borisrorsvort if I understood correctly you want to update the map's dimensions when the window resizes.
The best way to do that would be to extend the leaflet-map component with the `ResizeAware` mixin.

Example:
```js
import LeafletMapComponent from 'ember-leaflet/components/leaflet-map';
import ResizeAware from 'ember-resize/mixins/resize-aware';

export default LeafletMapComponent.extend(ResizeAware, {
  debouncedDidResize() {
    if (this._layer) {
      this._layer.invalidateSize();
    }
  }
});
```

`this._layer` is the raw instance of the leaflet map layer. More info on the `invalidateSize()` method: http://leafletjs.com/reference.html#map-invalidatesize

Feel free to reopen/comment if this didn't help you. :)

**Comment by borisrorsvort** [comment]
I didn't know you could do this :) I'll try that. Thanks!

**Comment by borisrorsvort** [comment]
:+1: that worked! Thanks :smile:

**Comment by v3ss0n** [comment]
i think i am saving the same problem , where to put that mixin? in initializers ?
