### ISSUE TITLE
Would be useful to have this scope bound to the component in leaflet events

### ISSUE THREAD

**Issue by ForSpareParts** [miguelcobain/ember-leaflet#42]
I frequently subclass ember-leaflet components to get some specific behavior, and as such, I have events that the component should handle itself. It'd be handy to be able to do this:

```js
export default BaseLayer.extend({
  onMouseover() {
    console.log(this.get('someValue'));
  }
});
```

At present, code like the above results in an error, as `this` is undefined. Instead, I have to use this workaround:

```js
export default BaseLayer.extend({
  init() {
    this._super(...arguments);
    this.set('onMouseover', () => console.log(this.get('someValue')));
  }
});
```

After investigating, it appears that the culprit is the InvokeActionMixin, which invokes all action functions with a `this` context of `undefined`. I get that that's more in line with ES6 semantics, but it also makes this use case awkward. Is there a better way to do what I'm trying to do, and if not, could we find some way to pass the component context along to the action handler?

**Comment by miguelcobain** [comment]
Notice here: https://github.com/miguelcobain/ember-leaflet/blob/master/addon%2Fcomponents%2Fbase-layer.js#L83

We invoke a method on the class named `'_' + eventName`. So, you can just create a method named `_click`, for example, and go with that.
There is a reason for the `_` prefix. Without it, some names would clash with already existing DOM events. `click` is already taken. `onClick` is for the actions. I came up with `_click` since it is a private-ish method.

Is this what you're looking for?

**Comment by ForSpareParts** [comment]
Ah, I missed that. Thanks!

This covers most of my cases, yes -- certainly everything directly related to the event system. There's a side case where layers take callbacks (rather than events) and I'd like to bind those callbacks to the component context, but that's more of an Ember problem -- the notion being that I want "methods" on a class that are actually functions bound permanently bound to the instance as `this`. I think I can get around it by making computed properties instead of methods.

**Comment by miguelcobain** [comment]
What kind of callbacks, for example?

**Comment by ForSpareParts** [comment]
At the moment, it's stuff like `style` and `forEachFeature` for GeoJSONLayer.

**Comment by miguelcobain** [comment]
I would accept a PR to add L.geoJson, btw. :)

**Comment by ForSpareParts** [comment]
Noted ;-)

**Comment by ForSpareParts** [comment]
It's actually turning out to be a surprisingly convoluted layer to *use*. Whereas other layers can take, for instance, visual properties like line weight and color, realistic GeoJSON use requires these functions -- and they, in turn, require a bit more understanding of the Leaflet API than is ideal. You have to know what to do with a raw `Layer` object, for instance. I can deal with it personally, but I am fast becoming my team's Leaflet Guy, and I don't want to assume other developers have that familiarity.
