### ISSUE TITLE
throttle zooming

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-leaflet#46]
On mobile Chrome, it's very easy to send lots and lots of zoom events really fast by using the finger-pinching method. As a result, and after some Chrome remote debugging, I can make the app stop functioning after sending off too many network requests for the map tiles.

I was thinking about debouncing zoom requests to `ember-leaflet` but not sure how to do that yet. Just wondering if you've got any leads I can try before going down the rabbit hole. Thanks!

**Comment by miguelcobain** [comment]
@SirZach you can debounce ember-leafet zoom actions just like any other ember action.
Example: http://www.ember-power-select.com/cookbook/debounce-searches
or even the same example "on steroids" using the awesome ember-concurrency: http://ember-concurrency.com/#/docs/examples/autocomplete

**Comment by SirZach** [comment]
@miguelcobain but I don't see where I have power to debounce or use `ember-concurrency` for zoom actions. It seems like all of that is handled completely within `ember-leaflet`

**Comment by miguelcobain** [comment]
@SirZach ember-leaflet doesn't do any debouncing at all. Like ember-power-select, that is a concern left to the user.

ember-leaflet sends the zoom actions. You need to use them and debounce an action. e.g Ember provides `Ember.run.debounce`.

**Comment by SirZach** [comment]
@miguelcobain right, I understand that ember-leaflet doesn't do debouncing but I don't know where I can debounce the actions that are sent to leaflet.js...

```hbs
{{#leaflet-map lat=lat lng=lng zoom=zoom onZoomstart=(action "debounceZoom")}}
  {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
{{/leaflet-map}}
```

But from what I've seen in ember-leaflet, `onZoomstart` will trigger leaflet.js actions and then call any actions associated to `onZoomstart` that I could then debounce but at that point it's too late since leaflet.js is going to start making its request for new map tiles.

**Comment by miguelcobain** [comment]
@SirZach I just understood what you need.

> I don't know where I can debounce the actions that are sent to leaflet.js...

ember-leaflet never sends "actions" to leaflet. When you zoom you are interacting directly with leaflet.
This is an interesting question, but totally related with leaflet.

You'll probably be able to do this "tile loading debouncing" by subclassing leaflet's tilelayer.

**Comment by SirZach** [comment]
Bummer. Ok, I'll try and dive in. Thanks.
