### ISSUE TITLE
Calculate and display route distance

### ISSUE THREAD

**Issue by kirantpatil** [miguelcobain/ember-leaflet#50]
Hello,

Is it possible to calculate the route distance between two places and display it ?

Thanks.

**Comment by miguelcobain** [comment]
@kirantpatil youmight want to check leaflet plugins here: http://leafletjs.com/plugins.html

ember-leaflet provides core leaflet functionality. Good news is that it can be extended.
There are some ember-leaflet addons that provide extra functionality: http://www.ember-leaflet.com/addons

If you ever such a routing the plugin, don't forget to create an ember-leaflet extension. :)
