### ISSUE TITLE
Issue with Leaflet 1.6

### ISSUE THREAD

**Issue by clem3109** [miguelcobain/ember-leaflet#500]
When I updated to Leaflet 1.6, the center of my map doesn’t follow the @lat @ lng that I update
Everything is fine when I come back to Leaflet  1.3.4.

**Comment by miguelcobain** [comment]
@clem3109 that's strange. All the tests are passing with leaflet 1.6.

Can you post a code example that fails or even better, create a pull request with a failing test?

**Comment by clem3109** [comment]
I found out it is a bug that came with the 1.5.0 version of Leaflet, I didn’t found any obvious change that can explain the bug in the change log (https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md). 

I shared my project with you, the behaviour should work like this : on click on a marker, the map should center the marker (and opens the associated modal page).
<LeafletMap> in application/template.hbs
on click action in application/controller.js
map values and functions in map/service.js
Position object in position/class.js

**Comment by clem3109** [comment]
Erratum: the bug comes with the 1.4 version of Leaflet, so it may be due to the "new Map.panInside method ([#6054](https://github.com/Leaflet/Leaflet/pull/6054) by daverayment) » commit, I’ll dig other there.

**Comment by miguelcobain** [comment]
It's 2022 and new ember-leaflet and leaflet version have come out. Closing this.
Please reopen if you feel like this is still an issue.
