### ISSUE TITLE
Leaflet icon/draggability bug, dragging object can be undefined for hidden markers (related to #77)

### ISSUE THREAD

**Issue by ludo-syt** [miguelcobain/ember-leaflet#513]
Hello there, I have an issue with the marker-layer "iconDidChange" observer, the "dragging" object is sometimes undefined.
Note that we use [Ember Leaflet Marker Cluster](https://github.com/canufeel/ember-leaflet-marker-cluster) and the bug appears in cluster mode. Hidden markers don't have the "dragging" property as they are not rendered, however iconDidChange is triggered for those markers.
Our markers are not draggable.

Maybe you can check that this._layer.dragging object is valid before calling enable/disable.
Leaflet doc says on "dragging" property : "Only valid when the marker is on the map" [Doc](https://leafletjs.com/reference-1.6.0.html#marker-dragging)

Thank you for your help

![image](https://user-images.githubusercontent.com/68739849/88392325-12bad000-cdbc-11ea-9650-d672d4143a11.png)
![image](https://user-images.githubusercontent.com/68739849/88392369-27976380-cdbc-11ea-8137-516dea32e0ea.png)

**Comment by miguelcobain** [comment]
@ludo-syt released a fix on version `4.1.1`.

**Comment by ludo-syt** [comment]
Thank you @miguelcobain
