### ISSUE TITLE
Only render markers which are currently visible

### ISSUE THREAD

**Issue by badazz91** [miguelcobain/ember-leaflet#52]
We have the situation, that we have to render a lot of markers (e.g. > 300). I could think of an optimization, that only markers which location is visible in the current "viewport" (depending on ```lat```, ```lng``` and ```zoom```) actually get rendered onto the map. I think this could boost the performance a lot, since the amount of markers gets significantly reduced.

What do you think? Is there any downside?

**Comment by miguelcobain** [comment]
@badazz91 it depends on your use case.

If there is a really great number of markers, that may prove to be more performant.


Implementing this in ember-leaflet is trivial. Just use the `onMoveend` action of `{{#leaflet-map` and check for the current bounds and filter the markers:
```js
onMoveend(e) {
  let bounds = e.target.getBounds();
  let markers = this.get('markers');
  //filter markers array
}
```
