### ISSUE TITLE
Support for drawing on maps

### ISSUE THREAD

**Issue by bimabima** [miguelcobain/ember-leaflet#55]
I am new to ember-leaflet and wondering how to implement drawing polygon, circle, polyline overlays (similar to Leaflet.draw) on maps.

**Comment by miguelcobain** [comment]
The best way would be to add that leaflet plugin to ember-paper.
Maybe @ForSpareParts has some helpful info on that.

**Comment by bimabima** [comment]
@miguelcobain, is there a way to use Leaflet.draw from within ember-leaflet ?

**Comment by localyost** [comment]
First off: Ember-leaflet is such a great extension! Thank you so much for your hard work!

@bimabima - I need to work with leaflet.draw too. Eventually I want to _try_ and develop actual modules for it and package it as an extension, but for now I have just extended `leaflet-map` and added the options `draw `and `editable` to `leafletOptions`

like this:

```
import Ember from 'ember';
import LeafletMap from 'ember-leaflet/components/leaflet-map';
/* global L */

export default LeafletMap.extend({
    L,
     addDrawOption: function(){
         this.get('leafletOptions').addObjects(['draw','editable']);
     }.on('init'),

```
and then when you instantiate a map in your hbs. document you can add these options

```
{{leaflet-map
drawControl=true
editable=true
}}
```

if you want to listen for draw events you can do something like this (for now) manually

```
listenForDrawEvents: function(){
  const self = this;
  this._layer.on('draw:drawstop', function (e) {
      self.sendAction('drawingFinishedAction')
  });
}.on('didRender) 
```

and

```
{{leaflet-map
drawControl=true
editable=true
drawingFinishedAction='handleDrawingFinishedAction'
}}
```

hopefully this isn't too hacky :)

**Comment by rogerschlachter** [comment]
@localyost Any chance you have a small example project?

**Comment by rogerschlachter** [comment]
when you say you extend leaflet-map, which file do you edit to do so? app/components/leaflet-map.js ?

what version of ember are you using?

Thanks!

**Comment by rogerschlachter** [comment]
Sorry for the spam...I think I've got it, but now the drawng buttons don't have symbols/icons in them. Ideas?

**Comment by localyost** [comment]
Hey, no problem :) 

I'm using Ember 2.4

I don't have the project in front of me, but if I remember correctly I installed it with bower and in `ember-cli-build.js` compiled the source + css 
```
app.import('bower_components/leaflet.draw/dist/leaflet.draw.js');
app.import('bower_components/leaflet.draw/dist/leaflet.draw.css');
```
and then added the image sprites like this:

`app.import('bower_components/leaflet.draw/dist/images/spritesheet.png', {destDir: 'assets/images'});`

I'll check tomorrow.

**Comment by rogerschlachter** [comment]
Thanks. That's exactly where I just ended up.
