### ISSUE TITLE
ember-leaflet not showing anything

### ISSUE THREAD

**Issue by broerse** [miguelcobain/ember-leaflet#557]
I am new to ember-leaflet and installed it in a new Ember App.

https://github.com/broerse/test-leaflet/blob/master/app/templates/application.hbs
https://github.com/broerse/test-leaflet/blob/master/app/controllers/application.js

It does not show a map or an error. I hope someone can take a look at what I am doing wrong. Thanks!

**Comment by miguelcobain** [comment]
It looks like you forgot to style the container.

On https://miguelcobain.github.io/ember-leaflet/docs/container we can read:
> **Reminder:** The leaflet map container needs to be styled to have some size. If you don't see any container at all, that's probably because you forgot to style it. You can target leaflet containers in css using the `.leaflet-container` class or providing an id or class attribute in your `<LeafletMap>` component.

Please reopen if this was not the culprit.

**Comment by broerse** [comment]
@miguelcobain Sorry, that was it. Thanks!
