### ISSUE TITLE
Support fitBoundsOptions

### ISSUE THREAD

**Issue by gandalfar** [miguelcobain/ember-leaflet#59]
From discussion on Slack, it would be useful if we could do this:

```hbs
{{#leaflet-map
  bounds=bounds
  fitBoundsOptions=(hash
    paddingTopLeft=(point 0 0)
    paddingBottomRight=(point 0 0)
    padding=10
    maxZoom=10
  )
}}
```

**Comment by miguelcobain** [comment]
It will a little more difficult than I initially thought.
`bounds` is in `leafletProperties` here: https://github.com/miguelcobain/ember-leaflet/blob/master/addon%2Fcomponents%2Fleaflet-map.js#L41

I created a "DSL" that let's me call a leaflet method when a certain property changes.
e.g `bounds:fitBounds` means "when `bounds` changes, call `fitBounds` with `bounds` as a parameter".

We *could* extend the DSL to allow multiple arguments.
e.g `bounds:fitBounds:fitBoundsOptions` means "when `bounds` changes, call `fitBounds` with `bounds` and `fitBoundsOptions` as a parameter".

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-leaflet/pull/60

**Comment by IAmJulianAcosta** [comment]
@miguelcobain I'm having problems setting `offset` property in popup. The property is passed to `L.popup`. I printed value in `L.popup.initialize` and is the value I used in template, but when rendering in `_updatePosition`, the value is class default, `0, -7`.

Any idea about why?
