### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-leaflet#63]
some recent changes should be mentioned in the docs (dummy app), notably:

- https://github.com/miguelcobain/ember-leaflet/pull/60 - `fitBoundsOptions` and `zoomPanOptions` by @gandalfar 
- https://github.com/miguelcobain/ember-leaflet/pull/62 - `popupOptions` by @IAmJulianAcosta 

## Where to put this info?

Most of the component pages are rendered dynamically, but each of them renders a component to show additional custom info, if the component exists.
The line responsible for that is: https://github.com/miguelcobain/ember-leaflet/blob/master/tests%2Fdummy%2Fapp%2Ftemplates%2Fdocs%2Fcomponent.hbs#L3-L5

It basically looks for a component named `${component-name}-example` and renders it if it exists.
There are already some existing examples: https://github.com/miguelcobain/ember-leaflet/tree/master/tests/dummy/app/templates/components

So, we need to write about these features using that approach on `leaflet-map` and `marker-layer` pages respectively.

**Comment by gandalfar** [comment]
Is this a style you'd like for documentation or just another item in "leaflet-map component supports the following options:"?
