### ISSUE TITLE
Adding custom properties to leafletOptions (leaflet-map)

### ISSUE THREAD

**Issue by IAmJulianAcosta** [miguelcobain/ember-leaflet#64]
Currently `leafletOptions` has hardcoded the leaflet options (`'center', 'zoom', 'minZoom', 'maxZoom', 'maxBounds', 'crs',...`), and doesn't allow to pass custom properties to the `map`.

I'm using `leaflet-zoomslider` that requires to pass `zoomsliderControl: true` when calling `L.map`. I solved it extending the component and pushing the string to `leafletOptions` on component init, but I think that this could be done in a better way :)

**Comment by miguelcobain** [comment]
The **ideal** thing to do here would be to create an addon like these: http://www.ember-leaflet.com/addons

That addon would:
  1. import Leaflet.zoomslider code into the app
  2. add `zoomsliderControl` property to `leafletOptions`

The best addon to take inspiration from would be [ember-leaflet-rotated-marker](https://github.com/miguelcobain/ember-leaflet-rotated-marker/). There I extend the functionality of `marker-layer`. You would extend the functionality of `leaflet-map`.

Then people would just `ember install ember-leaflet-zoomslider`, add `zoomsliderControl=true` and boom. Done. 😃
