### ISSUE TITLE
Opening marker popups via actions outside leaflet-map

### ISSUE THREAD

**Issue by lucacorti** [miguelcobain/ember-leaflet#65]
I have a number of markers with popups on a map, I want to open a specific popup programmatically from an action triggered outside the leaflet-map component in the same controller.

Is this possible? Does it require interacting with leaflet directly?

**Comment by IAmJulianAcosta** [comment]
Should work with `popupOpen`, but not working right now: https://github.com/miguelcobain/ember-leaflet/issues/69

**Comment by miguelcobain** [comment]
@lucacorti you should do it using the `popupOpen` property.
Check this demo: http://www.ember-leaflet.com/docs/templates
