### ISSUE TITLE
closePopupOnClick does not work with a flag

### ISSUE THREAD

**Issue by cedriclinares123** [miguelcobain/ember-leaflet#658]
Reproduction Steps
1) Use a flag set to false for the closePopupOnClick value in a leaflet map with popups
2) Trigger the flag so it becomes true
Expected: Popups will not close on map click
Result: Popups still close on map click

I can create a twiddle but this should be pretty simple to reproduce

**Comment by miguelcobain** [comment]
I see. Unfortunately Leaflet itself does not support changing `closePopupOnClick` option **after** map initialization. It's an initialization option only.
So, I think we're pretty much out of options here. Shouldn't be difficult to add a method like `setClosePopupOnClick()` to core leaflet.

Perhaps you could reopen an issue/PR [there](https://github.com/Leaflet/Leaflet) and link this issue.
