### ISSUE TITLE
Uncaught Error: Could not find module `ember-get-config` imported from `(require)`

### ISSUE THREAD

**Issue by muziejus** [miguelcobain/ember-leaflet#670]
[ This is a duplicate of #140, but my previous comment got no traction so I wonder if that did not reopen the issue ]

Weirdly, I'm getting this error again today:

```
Uncaught Error: Could not find module `ember-get-config` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at eval (ember-get-config.js:1)
    at Object.../externals/ember-get-config.js (chunk.bb72f027e0f3863f83da.js:1521)
    at __webpack_require__ (chunk.51f51e323db24546eaee.js:31)
    at eval (leaflet-assets.js:7)
    at Object../node_modules/ember-leaflet/initializers/leaflet-assets.js (chunk.dcb52b452f126908dff6.js:3081)
    at __webpack_require__ (chunk.51f51e323db24546eaee.js:31)
    at eval (leaflet-assets.js:6)
```

This is in the console, not in the build, which works fine. I've installed `ember-get-config` into my app, and the version matches the version in `ember-leaflet`'s `package.json`, but still nothing.

Ember 3.28.0 w/ Embroider (in case there is a building error)

_Originally posted by @muziejus in https://github.com/miguelcobain/ember-leaflet/issues/140#issuecomment-900636873_

**Comment by miguelcobain** [comment]
@muziejus which ember-leaflet version are you using?

**Comment by muziejus** [comment]
5.0.0-beta.3

**Comment by miguelcobain** [comment]
@muziejus I refactored in a way that doesn't need `ember-get-config` dependency, and as such it was removed.

Please try the newly released `5.0.0-beta.5` version.

**Comment by muziejus** [comment]
Thanks. I don't get that error anymore, now I get this one:

```
Error occurred:

- While rendering:
  -top-level
    application
      container
        animated-container
          -dynamic-element
            animated-if
              animated-value
                animated-each
                  ea-list-element
                    index
                      map
                        leaflet-map
```

```
opcode-compiler.js:285 Uncaught Error: Attempted to resolve `eq`, which was expected to be a helper, but nothing was found.
```

Manually installing `ember-truth-helpers` did the trick, but that doesn't look like it's a listed dep for this add-on.

**Comment by miguelcobain** [comment]
@muziejus can you try `5.0.0-beta.7`?
I removed the usage of the eq helper.

**Comment by muziejus** [comment]
Done. I uninstalled `ember-truth-helpers` and upgraded to beta 7. A map renders.

Thanks! Now there is a forest of deprecations, but I suppose you're aware of those.

**Comment by muziejus** [comment]
or would you like some help with them?

**Comment by miguelcobain** [comment]
@muziejus PRs are welcome, for sure!
