### ISSUE TITLE
Options to geojson not passed

### ISSUE THREAD

**Issue by josemarluedke** [miguelcobain/ember-leaflet#671]
It seems that options passed into `<layers.geojson>` is not passed into `L.geoJson`. 

I have the following template:

```       
       <layers.geojson
            @geoJSON={{data.shape}}
            @color="red"
            as |polygon|
          >
            <polygon.tooltip @sticky={{true}}>
              DANGER ZONE
            </polygon.tooltip>
          </layers.geojson>

```

I never get that color red option. I added a log into createLayer in `geojson-layer.js` and the output of options is empty:
```
    console.log('create geojson ', ...this.requiredOptions, this.options)
```

![image](https://user-images.githubusercontent.com/230476/138526222-307525b8-50e4-4e00-be9f-f1cb4e5a127b.png)

**Comment by miguelcobain** [comment]
This happens because `@color` is not a valid argument to the geojson layer: https://miguelcobain.github.io/ember-leaflet/docs/api/components/geojson-layer

What you can do is to use
```hbs
<layers.geojson
  @geoJSON={{data.shape}}
  @style={{this.shapeStyle}} as |polygon|>
```

and on the controller/component
```js
shapeStyle() {
  return { color: 'red' };
}
```
