### ISSUE TITLE
Deprecation - ensure-safe-component.string

### ISSUE THREAD

**Issue by m0glan** [miguelcobain/ember-leaflet#677]
Hello, we're using latest version of `ember-leaflet` 5.0.1 with Ember.js v3.28 LTS and we're getting the following deprecation:

> DEPRECATION: You're trying to invoke the component "popup-layer" by passing its name as a string. This won't work under Embroider. [deprecation id: ensure-safe-component.string]

I am not sure that it is coming from this addon, I just did a search for `popup-layer` and `tooltip-layer` and this is the addon they come up in.

**Comment by superlou** [comment]
I also see this deprecation warning on Ember 4.6.

**Comment by ivanterekh** [comment]
Same problem

**Comment by armin11** [comment]
same for me - the components could not be integrated

example message:

DEPRECATION: You're trying to invoke the component "tooltip-layer" by passing its name as a string. This won't work under Embroider. [deprecation id: ensure-safe-component.string] This will be removed in Ember embroider. See https://github.com/embroider-build/embroider/blob/main/REPLACING-COMPONENT-HELPER.md#when-youre-passing-a-component-to-someone-else for more details.

the map won't be shown
