### ISSUE TITLE
add control-layer/layers.control component

### ISSUE THREAD

**Issue by bartocc** [miguelcobain/ember-leaflet#68]
I could not find a way to add a control to the ember-leaflet map without writing my own ember component.

I guess a control-layer/layers.control component would be a nice addition the ember-leaflet.

Have you ever considered this?

**Comment by miguelcobain** [comment]
@bartocc are you looking for this addon? https://github.com/canufeel/ember-leaflet-layer-control

I personally don't like to use that control. I prefer to build my own control in ember-land using `{{#if`s.
