### ISSUE TITLE
Breaking changes using leaflet `1.8.0`

### ISSUE THREAD

**Issue by esbanarango** [miguelcobain/ember-leaflet#680]
<img width="1433" alt="Desks_·_Envoy" src="https://user-images.githubusercontent.com/1156865/187490707-81753935-a7ba-417d-97b0-e6143655496f.png">

🌍 Environment
ember-leaflet `2.3.2`
leaflet `1.8.0`
ember-source `4.6.0`

**Comment by esbanarango** [comment]
@miguelcobain Thank you for the fast follow-up. 🙏 . We will test it once a new release of ember-leaflet is out.

**Comment by miguelcobain** [comment]
@esbanarango I'm very sorry for the delay
I forgot to release. 

`5.0.2` is now released. Please let me know if you have any problems.
