### ISSUE TITLE
Help needed with an Embroider error

### ISSUE THREAD

**Issue by roomman** [miguelcobain/ember-leaflet#684]
Hello! I've just enabled Embroider for a project that uses this addon and am seeing the following error:
```
 Attempted to resolve `tile-layer` via ensureSafeComponent, but nothing was found.
```
I can see that the `leaflet-map` is utilising the `ensureSafeCompnent` helper so I can only assume that web pack isn't outputting the `tile-layer` component for whatever reason. Has anyone else come up against this and can you help me work out how to resolve the issue?

**Comment by miguelcobain** [comment]
@roomman can you try ember-leaflet >= 5.1.0 and close the issue it is fixed, please? :)

**Comment by roomman** [comment]
Excellent, thanks @miguelcobain, that's resolved the issue for me. I really appreciate your time. 🙏🏻
