### ISSUE TITLE
popupOpen=true not working

### ISSUE THREAD

**Issue by IAmJulianAcosta** [miguelcobain/ember-leaflet#69]
I'm trying to open a popup using `popupOpen`, but is not working. 
```
{{#marker-layer popupOpen=true}}
foo
{{/marker-layer}}
```

The following function never executes because `this._map`is `undefined` when executed.
```
openPopup: function () {
	if (this._popup && this._map && !this._map.hasLayer(this._popup)) {
		this._popup.setLatLng(this._latlng);
		this._map.openPopup(this._popup);
	}

	return this;
},
```

It seems that `openPopup` is executing before `L.marker.onAdd`, maybe `this.popupOpenDidChange` is executing too early (executed in `didCreateLayer`)?

**Comment by miguelcobain** [comment]
If you check this demo page: http://www.ember-leaflet.com/docs/templates

When you turn the `popupOpen` boolean, the popup opens.
Also, we have a test that makes sure that works here: https://github.com/miguelcobain/ember-leaflet/blob/master/tests%2Fintegration%2Fcomponents%2Fpopup-test.js#L90-L119

Can you provide a failing test?

**Comment by IAmJulianAcosta** [comment]
It seems that problem is related with `marker-cluster-layer` use, I will investigate more about it

**Comment by miguelcobain** [comment]
Maybe an issue in the plugin repo and a reference to this one would help.
