### ISSUE TITLE
Documentatiojn for @popupOpen?

### ISSUE THREAD

**Issue by MichalBryxi** [miguelcobain/ember-leaflet#690]
I noticed that on the [they're just templates](https://miguelcobain.github.io/ember-leaflet/docs/templates) documentation page, there is `marker.popup` argument `@popupOpen` used:

```
<LeafletMap as |layers|>
  <layers.marker as |marker|>
      <marker.popup @popupOpen={{this.isPopupOpen}}>
        foo
      </marker.popup>
    </layers.marker>
</LeafletMap>
```

I tried to find documentation for this attribute on [marker layer](https://miguelcobain.github.io/ember-leaflet/docs/api/components/marker-layer) and [popup-layer](https://miguelcobain.github.io/ember-leaflet/docs/api/components/popup-layer), but without any luck. The [source code](https://github.com/search?q=repo%3Amiguelcobain%2Fember-leaflet+popupOpen&type=code) seems to mention in in [base-layer](https://miguelcobain.github.io/ember-leaflet/docs/api/components/base-layer), but that one does not contain this property either. Moreover it's not obvious where does `<marker.popup>` come from - where should I be looking at?

Is this a missing piece of documentation or am I just looking at the wrong spot?

**Comment by miguelcobain** [comment]
> The [source code](https://github.com/search?q=repo%3Amiguelcobain%2Fember-leaflet+popupOpen&type=code) seems to mention in in [base-layer](https://miguelcobain.github.io/ember-leaflet/docs/api/components/base-layer)

That's the `onPopupopen` action. Not related with the popup layer's `@popupOpen` argument.
I added that argument documentation on the `<PopupLayer />` docs.
![image](https://github.com/miguelcobain/ember-leaflet/assets/631691/d929de31-b724-4e99-a07e-8fef0c5354c5)

> Moreover it's not obvious where does <marker.popup> come from - where should I be looking at?

I also added docs to the components that the `InteractiveLayer` yields (which MarkerLayer, ImageLayer and PathLayer extend from).

![image](https://github.com/miguelcobain/ember-leaflet/assets/631691/70bc830e-8e5e-46ac-b6c2-84f4b564a0c8)

The API docs could be improved, for sure. With more examples and detail on everything. PRs are welcome!
