### ISSUE TITLE
didnt see anything in the screen

### ISSUE THREAD

**Issue by marendra** [miguelcobain/ember-leaflet#7]
i need help, after installing ember-leaflet and put the template like this bellow :
    {{#leaflet-map lat=lat lng=lng zoom=zoom}}
       {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
    {{/leaflet-map}}}

and put in some javascript

export default Ember.Controller.extend({
  lat: 45.519743,
  lng: -122.680522,
  zoom: 10
});

after i run ember server, the web didnt show anything, even the error
im using :
version: 1.13.13
node: 5.1.0
npm: 2.14.10
os: darwin x64

thanks

**Comment by miguelcobain** [comment]
@marendra 

- In what files did you put the handlebars and javascript?
- Is there an ember-leaflet entry in your package.json?
- Is there a leaflet entry in your bower.json?

**Comment by marendra** [comment]
i put handlebars in index.hbs and the javascript in index.js (controllers path),
yes there is ember leaflet in my package.json , "ember-leaflet": "2.0.6" 
yes there is ember laflet in my bower.json "leaflet": "~0.7.7"

**Comment by paddleman** [comment]
Styling perhaps?

....from @miguelcobain 's excellent [ember-leaflet guides] (http://www.ember-leaflet.com/docs/container)

> Reminder: The leaflet map container needs to be styled to have some size. If you don't see any container at all, that's probably because you forgot to style it. You can target leaflet containers in css using the .leaflet-container class or providing an id or class attribute in your {{#leaflet-map component.

**Comment by marendra** [comment]
@paddleman ow man i forgot that, thanks
