### ISSUE TITLE
latLngToLayerPoint & other conversions?

### ISSUE THREAD

**Issue by Busata** [miguelcobain/ember-leaflet#71]
Hi,

I'm fairly new to ember & this library, I noticed on leaflet that there are certain conversion methods available for maps such as latLngToLayerPoint, are they included in this library & can they be accessed somehow?

**Comment by miguelcobain** [comment]
Yes, because leaflet itself is included.
That method belongs to the leaflet map instance. At what point do you need to call that method on the map?
you can use onload action to get a leaflet map instance as soon as it loads (there are some issues here that explain how to use that action). You can then save the leaflet map instance for lateral reference.

I'll close this, but if this didn't solve your problem, feel free to reopen.

**Comment by Busata** [comment]
I have a pop up menu that should move along with the marker when I drag it, so I suppose this is the only way to get the offset x/y for the marker (dragend event). Thanks!

**Comment by miguelcobain** [comment]
@Busata please explain your use case better. You want to move a popup with the marker?
If that's the case why dont't you just use the normal marker-layer component with a block template. The block template will create a popup bound to that marker.

There may be an easier way. I'd like to help if that's the case. :)

**Comment by Busata** [comment]
Possibly, what I have now by manually syncing the menu with the marker upon map/marker events:
http://imgur.com/GGcg2sD (8MB gif, not sure how fast it loads)
So that would be possible with what you said?

**Comment by miguelcobain** [comment]
@Busata i see. What kind of element is the text box? A normal div or is it some leaflet layer?

**Comment by Busata** [comment]
it's a fixed position div, so I have the freedom to style & animate as I want. Unless that is possible with normal leaflet layers too? (though I don't see it being in the scope of what leaflet can/should do)

**Comment by miguelcobain** [comment]
@Busata then, yes, I think this is the better way.
Recap:
- use the `ondrag` action,
- get the pixel location from the new marker latlng using leaflet's methods (leaflet map instance and marker are available in the action arguments)
- set those pixels to a property
- those properties eventually end up in a component which binds the `style` attr?

Example:
```hbs
{{#leaflet-map ...}}
  {{marker-layer lat=lat lng=lng ondrag=(action "updateTooltipPosition")}}
  {{#if showTooltip}}
    {{tooltip top=tooltipTop left=tooltipLeft}}
  {{/if}}
{{/leaflet-map}}
```

```js
export default Component.extend({
  attributeBindings: ['positionStyle:style'],
  positionStyle: computed('top', 'left', function() {
    return htmlSafe(`top: ${this.get('top')}px; left: ${this.get('left')}px`);
  })
});
```

**Comment by Busata** [comment]
yep, that's pretty much how I do it now(except for the way you bind the position, that is nicer than how I did it.. For future reference, you also need to bind some events on the map itself (zoom, drag), the tooltip will remain static otherwise

Thanks!

**Comment by miguelcobain** [comment]
@Busata you might want to use `onmove` instead of `zoom` *and* `drag`. move triggers whenever the map moves, being it because of a zoom, drag, or whatever.
