### ISSUE TITLE
Polyline not displaying

### ISSUE THREAD

**Issue by dougajmcdonald** [miguelcobain/ember-leaflet#76]
Firstly, thanks for the library. Also the example on http://www.ember-leaflet.com/ is excellent

I was trying to extend the example by adding a line between two markers and tried to add a polyline layer like this:

      {{#leaflet-map lat=lat lng=lng zoom=zoom as |layers|}}
                    {{#layers.polyline locations=markers weight=3 color="red"}}
                    {{/layers.polyline}}  
      {{/leaflet-map}}

But unfortunately nothing shows up.

I had a look over the leaflet API but am having trouble relating all of that to the ember-leaflet version.

Could you provide an example? or point me in the right direction for adding a line between my two markers please?

**Comment by dougajmcdonald** [comment]
I should clarify that my markers themselves show up, it's just the path between the two.

**Comment by miguelcobain** [comment]
@dougajmcdonald what is the content of `markers` property?

**Comment by dougajmcdonald** [comment]
@miguelcobain my 'markers' property is the equivalent of the 'dangerZone' property in the example. Shown below with the locations array it's mapped from.

```
    locations: Ember.A([
        { name: 'Transmitter', lat: 59.9000, lng: 10.7446}, 
        { name: 'Receiver', lat: 51.4454, lng: -2.5840}
    ]),
    
    markers: Ember.computed('locations.@each.lat', 'locations.@each.lng', function() {
        return this.get('locations').map(x => ({ lat: x.lat, lng: x.lng }));
    }),
```

**Comment by dougajmcdonald** [comment]
@miguelcobain in case it's of any help in diagnosing the issue, I added a third location and have tried switching the layer between polygon and polyline and changing between the:

`{{layers.polyline locations=markers color="red"}}  `

and 

```
{{#layers.polyline locations=markers color="red"}}  
{{/layers.polyline}}
```

And nothing seems to show for either layer.

I'm using:

`    "ember-leaflet": "2.2.6",`

**Comment by miguelcobain** [comment]
I just tried changing `polygon` to `polyline` in the demo app and it works accordingly.

Can you confirm that your `markers` computed did run and computed the expected values?

**Comment by dougajmcdonald** [comment]
I did think perhaps it wasn't being called, I've console.logged the call to `this.get('locations').map(...) ` and I get an array with three objects, with two properties each, 'lat' and 'lng'

![image](https://cloud.githubusercontent.com/assets/1190042/15897174/56a63a46-2d8b-11e6-906c-0e81a43d9a54.png)

Is this what you'd expect?

**Comment by miguelcobain** [comment]
@dougajmcdonald this is very strange.

Everything looks correct.

We have two options here:
1. you PR a failing test that demonstrates the issue
2. you provide an app where I can reproduce the issue and debug it for you (`ember new leaflet-test` or wtv)

**Comment by dougajmcdonald** [comment]
@miguelcobain thanks for the help thus far. I will do my best to package an app up. 
Afraid I'm new to ember this week, so not 100% sure what the minimum I can send you that will be useful! 
I don't want to package up all the node_modules for obvious reasons!
[client.zip](https://github.com/miguelcobain/ember-leaflet/files/305129/client.zip)

**Comment by dougajmcdonald** [comment]
@miguelcobain can you confirm when you've grabbed the project as I'd rather not leave it up too long, cheers.

**Comment by miguelcobain** [comment]
@dougajmcdonald you have global styles that target svg elements. Those styles were colliding with leaflet's svg path rendering.
If I remove the styles, the polyline appears.

You need to be careful when writing styles that global.

**Comment by dougajmcdonald** [comment]
Gah #facepalm# those styles were purely to demo something quickly before refining things later on.

Sorry for wasting your time
