### ISSUE TITLE
Tiles loaded partially

### ISSUE THREAD

**Issue by patuku-roy** [miguelcobain/ember-leaflet#8]
@miguelcobain I've tried to put the basic map but the tiles loaded partially, this is my template:

```
{{#leaflet-map lat=model.location.lat lng=model.location.lng zoom=15 zoomControl=false attributionControl=false id="map-body"}}
        {{tile-layer url=mapURL}}
        {{#marker-layer lat=model.location.lat lng=model.location.lng}}{{/marker-layer}}
{{/leaflet-map}}
```

And this is the result:

![file 28-11-15 15 37 43](https://cloud.githubusercontent.com/assets/12027241/11455845/002180b4-96a4-11e5-8c62-4b608a8dece9.png)

Maybe you can give me some direction how to solve this problem, thanks in advance.

**Comment by miguelcobain** [comment]
What styles are being used in map-one id?

**Comment by patuku-roy** [comment]
You mean the mapURL? I'm using mapbox for the tiles and I chance to cartodb once and the tiles still unloaded. The mapbox style is mapbox.streets

**Comment by miguelcobain** [comment]
This usually happens when the map container changes its dimensions after the first render. Maybe that happened after an orientation change?
I was asking for css styles you're using for the map container.

**Comment by patuku-roy** [comment]
No style for that map except inline style using `Ember.$.("#map-body").height(xxx)` and I locked to portrait position.

**Comment by miguelcobain** [comment]
@patuku-roy I think we discovered the problem.

When leaflet initializes, it measures its container size using javascript. This allows leaflet to know its boundaries. This way it can hide unseen tiles, markers, and other performance optimizations.

You're dynamically setting a height, but that probably happens after leaflet initializes.
To confirm this theory you can set two breakpoints:
- one here https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/leaflet-map.js#L78
- and the other at your `Ember.$.("#map-body").height(xxx)`

You will probably see that the leaflet map is created before you set your height.

Solutions:
- ideally, you should set the container size before leaflet initializes. If possible use css.
- if your really need to set the map's height dynamically, you may need to extend `leaflet-map` and use `this.$().height(xxx)` in an overridden `didInsertElement`.

**Comment by patuku-roy** [comment]
Thanks @miguelcobain
