### ISSUE TITLE
locations.[] objects vs array

### ISSUE THREAD

**Issue by donaldwasserman** [miguelcobain/ember-leaflet#83]
In the leaftlet library, you can pass in an array of arrays into `locations.[]` I can only get `{lat: xx, lng: xxx}` objects to work. 

Does this addon support passing arrays into locations? (ie: `[-43.123, 71.123]`). 

This is a fantastic library otherwise.

**Comment by miguelcobain** [comment]
@donaldwasserman to which kind of layer you want to pass in an array of arrays?

**Comment by donaldwasserman** [comment]
Polyline

**Comment by miguelcobain** [comment]
I didn't see any reason of why this wouldn't work.
I've added this test that proves that it works: https://github.com/miguelcobain/ember-leaflet/blob/master/tests/integration/components/array-path-layer-test.js#L119-L138

You have two options:
- submit a failing test PR so I can work on fixing it
- provide a demo app that reproduces the problem

**Comment by donaldwasserman** [comment]
I followed up on this after I wasn't on deadline for a project, and I realized I was passing lng/lat rather than lat/lng. 

Thanks for the quick reply on the ticket.

Apologies for the ticket.
