### ISSUE TITLE
leaflet-routing-machine

### ISSUE THREAD

**Issue by kirantpatil** [miguelcobain/ember-leaflet#84]
Hi,

Does ember-leaflet uses leaflet-routing-machine plugin to find the way from A to B on a Leaflet map ?

Thanks.

**Comment by miguelcobain** [comment]
That is a leaflet plugin you need to integrate. You can find several examples of such integrations in the addons section.

**Comment by kirantpatil** [comment]
Hi @miguelcobain,  If you have any guideline how to add leaflet plugin to ember plugin/addon, please share it. I would like to start working on this issue.

**Comment by miguelcobain** [comment]
@kirantpatil the best guide I can think of is the source code of one of the many ember-leaflet addons.
once you learn how to create ember-cli addons, then check one of those addon source code to understand how they're built.

This would make a very nice plugin.

**Comment by kirantpatil** [comment]
Yes @miguelcobain Sir, I am in that direction.
https://github.com/kirantpatil/ember-leaflet-routing-machine

**Comment by kirantpatil** [comment]
@miguelcobain shall we discuss about this issue at http://discuss.emberjs.com/t/ember-leaflet-routing-machine-addon/11023
