### ISSUE TITLE
ember.debug.js:15678 Uncaught Error: Assertion Failed: You must provide either valid `bounds` or a `center` (or `lat`/`lng`) and a `zoom` value

### ISSUE THREAD

**Issue by smitakiran25** [miguelcobain/ember-leaflet#85]
I am getting the following error i am trying to display hospital locations and getting the longitude and longitude from the firebase i am using 
ember-cli :v2.6.0
OS: Fedora 20

**app/template/gmap.hbs**

{{#leaflet-map lat=lat lng=lng zoom=zoom}}

{{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
  <ul>
  {{#each model as |c|}}
  {{#layers.marker lat=c.latitude lng=c.longitude draggable=true}}
  {{/layers.marker}}
  {{/each}}
</ul>
{{/leaflet-map}}

**app/controller/newcase.js**
import Ember from 'ember';
export default Ember.Controller.extend({
  actions:{
    addCase: function() {
      var hname = this.get('hname');
      var location = this.get('location');
      var latitude = this.get ('latitude');
      var longitude = this.get('longitude');
   var newCase = this.store.createRecord('case', {
       hname : hname,
       location : location,
       latitude : latitude,
       longitude : longitude
     });
    newCase.save();
  this.setProperties({
    hname: ' ',
    location: ' ',
    latitude: ' ',
    longitude: ' '
  });
  }
 }
});

**app/controller/gmap.js**

import Ember from 'ember';
export default Ember.Controller.extend ({
});

**app/model/case.js**
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
export default Model.extend({
  hname : attr('string'),
  location: attr('string'),
  latitude: attr('number'),
  longitude: attr('number')
});

**app/route/newcase.js**
import Ember from 'ember';
export default Ember.Route.extend({
model: function() {
  return this.get('store').findAll('case');
}
});

![image](https://cloud.githubusercontent.com/assets/11611902/16456700/6a8a13e6-3e36-11e6-9068-7610b94e3205.png)

Please tell me what are the mistakes i did and how to display that locations pulling the lat and long from the firebase

**Comment by codyjroberts** [comment]
In your `gmap.hbs` template it doesn't appear that there are values for lat, lng, and zoom.  You may want to provide defaults in your controller if you're setting the coordinates based on geolocation.

**Comment by smitakiran25** [comment]
Thank you,

**Comment by smitakiran25** [comment]
thank you @codyjroberts  I resolved the error by adding default lat and lng in the controller now map is displaying
