### ISSUE TITLE
tiles caching addon 

### ISSUE THREAD

**Issue by pavloo** [miguelcobain/ember-leaflet#88]
Hey. First of all, thanks for the great project. I created an ember addon that wraps [Leaflet.TileLayer.PouchDBCached](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached), which is Leaflet plugin and lets you cache map tiles using PouchDB. Here it is [ember-leaflet-tiles-cache](http://github.com/pavloo/ember-leaflet-tiles-cache) . If you think this addon is okay, would be great if it could be included on [addons page](http://www.ember-leaflet.com/addons).

Thank you.

**Comment by miguelcobain** [comment]
Looks awesome!

ember-leaflet's website is on this repo as well (it's the dummy app).
You can PR the change on the addon list.

Here is the file: https://github.com/miguelcobain/ember-leaflet/blob/master/tests/dummy/app/templates/addons.hbs
