### ISSUE TITLE
Access to map instance, unproject coordinates ?

### ISSUE THREAD

**Issue by multiplegeorges** [miguelcobain/ember-leaflet#89]
Hi all,

Is there a way to get a reference to the Leaflet map instance?

I need to render an image using `L.CRS.Simple` and I need to unproject the pixel height and width of the image to the map's coordinate system.

Here's a simplified version of what I am doing now. Note, I am *not using ember-leaflet* right now, but I'd like to replicate this using the addon.

```javascript
    let w = this.get('document.width')
    let h = this.get('document.height')
    let url = this.get('document.preview')

    let zoomMap = L.map(this.get('mapId'), {
      minZoom: -2,
      maxZoom: 6,
      zoom: 1,
      crs: L.CRS.Simple
    })

    let center = zoomMap.unproject([w/2, h/2])
    zoomMap.setView(center)

    // calculate the edges of the image, in coordinate space
    var southWest = zoomMap.unproject([0, h], zoomMap.getMaxZoom() - 5)
    var northEast = zoomMap.unproject([w, 0], zoomMap.getMaxZoom() - 5)
    var bounds = new L.LatLngBounds(southWest, northEast)

    L.imageOverlay(url, bounds).addTo(zoomMap)

    // tell leaflet that the zoomMap is exactly as big as the image
    zoomMap.setMaxBounds(bounds)
```

Thoughts?

**Comment by miguelcobain** [comment]
@multiplegeorges does the `getBounds()` method help in your case? http://leafletjs.com/reference.html#map-getbounds

It returns the current boundaries in lat lng coordinates.

**Comment by multiplegeorges** [comment]
The desired outcome is something like this: http://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html

We have large ~5000x5000px images that we want to pan/zoom and Leaflet works very well for this.

>  does the getBounds() method help in your case?

The code I included above works perfectly. However, *if I were to use ember-leaflet* instead, how would I get a reference to the Leaflet map instance object being displayed on the page. 

If I have:

```handlebars
{{#leaflet-map center=center crs="L.CRS.Simple"}}
  {{image-layer url=url}}
{{/leaflet-map}}
```

```javascript
export default Ember.Component.extend({
  center: Ember.computed(function(){
    return map.unproject([w/2, h/2])
  })
});
```

How can I get a reference to the Leaflet map instance inside my Ember component in order to set the center?

**Comment by multiplegeorges** [comment]
Nevermind, I found that I can do the coordinate projection directly using the `L.CRS.Simple` class. No instance of the map is needed.

Thanks for your attention, feel free to close this.

**Comment by chris-aeviator** [comment]
@multiplegeorges I'm facing the same problem, I want to position a marker overlay by x,y coordinates set as posX, posY params to the component. I'm using crs.simple & cannot find a way to get this working in ember 3.0 & firefox (i was able to hack my way up to .unproject but it's breaking in firefox).

How did you do the access to L.CRS.Simple (.unproject) from within a component??
