### ISSUE TITLE
overriding  default option for leaflet map and adding control

### ISSUE THREAD

**Issue by karimsqualli** [miguelcobain/ember-leaflet#94]
hello everyone, so  i want to override default option provided to map in the component rather than specifying each option in template, and i want to add some leaflet control, what  i tryed to subclass leaflet-map components, i created a new component in my project : 

`import Ember from 'ember';
import EmberLeafletMap from 'ember-leaflet/components/leaflet-map';

export default EmberLeafletMap.extend({
  lat: 45.519743,
  lng: -122.680522,
  zoom: 14,
  center: [34.02944,-5.00749],
  minZoom: 12,
  maxBounds: [
    [33.92513, -5.088902,],
    [34.09489, -4.914494,]
  ],

});
`

but the problem is that i don't know how to use it, normally when i want to use leaflet map i write a block helper : `{{#leaflet-map lat=lat
  lng=lng
  zoom=zoom
  minZoom=minZoom
  maxBounds=maxBounds
  center=}}
  {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
{{/leaflet-map}}
`
i'm new to ember, and thanks

**Comment by miguelcobain** [comment]
You're doing it correctly. What is the name and directory of that file you created?

**Comment by karimsqualli** [comment]
==> app/component/leaflet-map.js

i didn't created a template file for this component, but i gived me an error, so i created  the template file, and copied its content from the template in ember-leaflet source, and its worked, i don't know if its the right way to do it.

another thing, when i want to load the data for the map (some marker just for testing) i have the possibility to do it in the router or in the component, but i have read that it anti-pattern to do it in the component, but the problem is that i want my map to be self contained, for exempla lets say i have a map of a city ,so i always add the  same markers to the map, i will have a lot a redunancy if i want to load the map in 4 or 5 differente template, i will have to repeat the code for fetching data(models) in the router and repeat the template code for adding marker to the map.

Thanks you.

**Comment by miguelcobain** [comment]
@karimsqualli 

1 create a file `app/components/my-leaflet-map.js`
```js
import LeafletMapComponent from 'ember-leaflet/components/leaflet-map';

export LeafletMapComponent.extend({
  lat: 45.519743,
  lng: -122.680522,
  zoom: 14,
  minZoom: 12
  // set any properties you want as default here
});
```
2 use the component normally and it will have the default options set
```hbs
{{#my-leaflet-map}}
  {{!-- add layers here --}}
{{/my-leaflet-map}}
```

I've noticed that in your example you set both center and lat/lng. That doesn't make a lot of sense to me.

**Comment by karimsqualli** [comment]
thanks.
