### ISSUE TITLE
Examples in http://www.ember-leaflet.com/docs/templates do not work with Leaflet 1.0.0-rc

### ISSUE THREAD

**Issue by devotox** [miguelcobain/ember-leaflet#97]
The problems are in clicking the elements to show the popups. 

Error: Cannot get 'style' of undefined

**Comment by miguelcobain** [comment]
Everything is working great over here.

Which *ember-leaflet* version are you using?
Only v2.2.8-beta.1 is compatible with leaflet 1.

**Comment by devotox** [comment]
ha that would make sense i was using 2.2.7. thank you updating now

**Comment by devotox** [comment]
I upgraded to 2.2.8-beta.1 and everytime i click on a polygon i get this

Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by miguelcobain** [comment]
@devotox can you please tell me the `leaflet` version in you `bower.json` file and the `ember-leaflet` version in your `package.json` file?

**Comment by devotox** [comment]
leaflet: 1.0.0-rc.2 & have tried 1.0.0-rc.3

ember-leaflet: 2.2.8-beta.1 & have tried 2.2.7
