### ISSUE TITLE
How would you set the position of the zoom Control?

### ISSUE THREAD

**Issue by devotox** [miguelcobain/ember-leaflet#98]
it seems that i get `Uncaught Error: Map container is already initialized.(…)`

if i try to do something like `L.map("main-map").zoomControl.setPosition('topright')`

**Comment by miguelcobain** [comment]
that happens because you're trying to initialize the same map again.
You need to access the current map instance and use `map.zoomControl.setPosition('topright');`.
There are many issues here on how to access the map instance. Most likely you'll want to use the onLoad action or subclass the map component.

**Comment by devotox** [comment]
I tried what you said and did something like this to no avail

```javascript

		initMap(event) {
			console.log(event);
			let map = event.target;
			this.set('map', event.target);

			map.zoomControl.setPosition('topRight');
		},
```

but get this error `Uncaught TypeError: Cannot read property 'appendChild' of undefined`

**Comment by miguelcobain** [comment]
What calls initMap?

**Comment by devotox** [comment]
```handlebars
	{{#leaflet-map
		onLoad=(action "initMap")
		onClick=(action "createMarker")
		onDragend=(action "endCreateZone")
		onDragstart=(action "startCreateZone")
		lat=lat lng=lng zoom=zoom as |layers|}}
		{{layers.tile url=mapUrl}}
```

**Comment by miguelcobain** [comment]
Hmm, that should work. Maybe the zoom control isn't yet created on load. What you could do is to set zoom control creation to false and then created one yourself and add it to the map in the correct position.

**Comment by devotox** [comment]
Ha i actually just found out the issue i was using camelcase and it is meant to be all lowercase. Thank you

**Comment by gnclmorais** [comment]
I just ran into this and it tool me a while to understand what the error was, so I’ll make it clearer…

The position string must be _all lowercase_, i.e., `'topRight'` → `'topright'`.
